<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Bins\Old\**" />
    </ItemGroup>

  <ItemGroup>
    <Compile Include="EvalTypes.fs" />
    <Compile Include="EvalLabel.fs" />
    <Compile Include="Sgd\SorterPoolMeasure.fs" />
    <Compile Include="Sgd\SorterMutationSource.fs" />
    <Compile Include="Sgd\SorterPoolTag.fs" />
    <Compile Include="Sgd\SgdStandard\SpMember_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SorterPool_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SpMemberHistory_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SpHistory_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\PoolEvalFunctions_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SorterPoolSet_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\MhMap_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\Spsh_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\PoolRunner_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\Pipeline_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SpDescription_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SpSummary_Standard.fs" />
    <Compile Include="Sgd\SgdStandard\SpSummarySet_Standard.fs" />
    <Compile Include="Sgd\SgdSoss\SpMember_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SorterPool_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SpMemberHistory_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SpHistory_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\PoolEvalFunctions_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SorterPoolSet_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\MhMap_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\Spsh_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\PoolRunner_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\Pipeline_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SpDescription_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SpSummary_Soss.fs" />
    <Compile Include="Sgd\SgdSoss\SpSummarySet_Soss.fs" />
    <Compile Include="SorterSelection.fs" />
    <Compile Include="SorterEvalBinStats.fs" />
    <Compile Include="SorterStageStats.fs" />
    <Compile Include="bins\CommonSgdBins.fs" />
    <Compile Include="Bins\SorterEvalKey.fs" />
    <Compile Include="Bins\BinsSoss\SorterEvalBin_Soss.fs" />
    <Compile Include="Bins\BinsSoss\SorterPoolBins_Soss.fs" />
    <Compile Include="Bins\BinsSoss\SorterEvalBinSet_Soss.fs" />
    <Compile Include="Bins\BinsSoss\SorterPoolBinsSet_Soss.fs" />
    <Compile Include="Bins\BinsSoss\SorterPoolBinsSetSeries_Soss.fs" />
    <Compile Include="Bins\BinsStandard\SorterEvalBin_Standard.fs" />
    <Compile Include="Bins\BinsStandard\SorterPoolBins_Standard.fs" />
    <Compile Include="Bins\BinsStandard\SorterEvalBinSet_Standard.fs" />
    <Compile Include="Bins\BinsStandard\SorterPoolBinsSet_Standard.fs" />
    <Compile Include="Bins\BinsStandard\SorterPoolBinsSetSeries_Standard.fs" />
    <Compile Include="Sgd\OutputUnions.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="6.0.0-beta001" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeneSort.Core\GeneSort.Core.fsproj" />
    <ProjectReference Include="..\GeneSort.Model.Sortable.V1\GeneSort.Model.Sortable.V1.fsproj" />
    <ProjectReference Include="..\GeneSort.Model.Sorting.V1\GeneSort.Model.Sorting.V1.fsproj" />
    <ProjectReference Include="..\GeneSort.SortingOps\GeneSort.SortingOps.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="11.0.101-rc1.26425.128" />
  </ItemGroup>

</Project>
