namespace GeneSort.Dispatch.V1

open System
open System.Threading
open FSharp.UMX
open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Model.Sorting.Sorter.Ce
open GeneSort.Model.Sorting.Sorter.Si
open GeneSort.Model.Sorting.Sorter.Uf4
open GeneSort.Model.Sorting.Sorter.Rs
open GeneSort.Model.Sorting.Sorter.Uf6
open GeneSort.Model.Sorting
open GeneSort.Model.Sortable
open GeneSort.SortingOps
open GeneSort.SortingResults
open GeneSort.SortingResults.Bins
open GeneSort.Db.V1
open GeneSort.Project.V1
open GeneSort.FileDb.V1
open OpsUtils
open GeneSort.Model.Sorting.V1


/// Host type for RandomSorterBins to manage environment-specific spans and filtering
type randomSorterBinsHost = 
    private { 
        _projectDb: IGeneSortDb 
        _parameterSpans: (string * string list) list
        _filter: runParameters -> runParameters option
    }
    static member Create db spans filter =
        { _projectDb = db; _parameterSpans = spans; _filter = filter }

    member this.ProjectDb = this._projectDb
    member this.ParameterSpans = this._parameterSpans
    member this.Filter = this._filter

    member this.ExtractDomainParams (rp: runParameters) =
        maybe {
            let! smk = rp.GetSimpleSorterModelType()
            let! sw = rp.GetSortingWidth()
            let! sl = rp.GetStageLength()
            let! cl = rp.GetCeLength()
            let! sc = rp.GetSorterCount()
            let! sdt = rp.GetSortableDataFormat()
            return (smk, sw, sl, cl, sc, sdt)
        }

module RandomSorterBins =

    let projectName = "RandomSorterBins" |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomSorterBins\\Data" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "RandomSorterBins, generated by Msce, Mssi, Msrs, and Msuf"
    
    let collectNewSortableTests = false
    let samplesPerBin = 1
    let rngFactory = rngFactory.LcgFactory
    let excludeSelfCe = true
    let allowOverwrite = false |> UMX.tag<allowOverwrite>

    // --- Helpers ---

    let getStageLength (sw: int<sortingWidth>) : int<stageLength> =
        match %sw with
        | 4 -> 5 | 6 -> 20 | 8 -> 40 | 12 -> 80 | 16 -> 100 
        | 18 -> 120 | 20 -> 130 | 22 -> 140 | 24 -> 200 
        | _ -> failwithf "Unsupported sorting width: %d" %sw
        |> UMX.tag

    let private sorterModelTypeForSortingWidth (rp: runParameters) =
        let smt = rp.GetSimpleSorterModelType().Value
        let sw = rp.GetSortingWidth().Value
        let has2factor = (%sw % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sw)
        let isMuf6able = (%sw % 3 = 0) && (MathUtils.isAPowerOfTwo (%sw / 3))

        match smt with
        | simpleSorterModelType.Msce -> Some rp
        | simpleSorterModelType.Mssi | simpleSorterModelType.Msrs -> if has2factor then Some rp else None
        | simpleSorterModelType.Msuf4 -> if isMuf4able then Some rp else None
        | simpleSorterModelType.Msuf6 -> if isMuf6able then Some rp else None
        | _ -> None

    let paramMapFilter (rp: runParameters) = 
        Some rp |> Option.bind sorterModelTypeForSortingWidth

    // --- Configurations ---

    module P1 =
        let spans = [
            (runParameters.sortingWidthKey, ["16"])
            (runParameters.simpleSorterModelTypeKey, [simpleSorterModelType.Msce] |> List.map SimpleSorterModelType.toString)
            (runParameters.sortableDataFormatKey, [sortableDataFormat.BitVector512] |> List.map SortableDataFormat.toString)
            (runParameters.sorterCountKey, ["100"])
        ]
        let host = randomSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    module P2 =
        let spans = [
            (runParameters.sortingWidthKey, [18; 20] |> List.map string)
            (runParameters.simpleSorterModelTypeKey, [sorterModelType.Msce; sorterModelType.Mssi; sorterModelType.Msrs; sorterModelType.Msuf4; sorterModelType.Msuf6] |> List.map SorterModelType.toString)
            (runParameters.sortableDataFormatKey, [sortableDataFormat.BitVector512] |> List.map SortableDataFormat.toString)
            (runParameters.sorterCountKey, ["10000"])
        ]
        let host = randomSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    // --- Logic ---

    let makeQueryParams repl sw smt outputDataType =
        queryParams.create (Some projectName) repl outputDataType
            [| (runParameters.sortingWidthKey, sw |> SortingWidth.toString); 
               (runParameters.simpleSorterModelTypeKey, smt |> Option.map SimpleSorterModelType.toString |> UmxExt.stringToString) |]

    let makeQueryParamsFromRunParams (rp: runParameters) (odt: outputDataType) =
        makeQueryParams (rp.GetRepl()) (rp.GetSortingWidth()) (rp.GetSimpleSorterModelType()) odt

    let enhancer (rp : runParameters) : runParameters =
        let sw = rp.GetSortingWidth().Value
        let smt = rp.GetSimpleSorterModelType().Value
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        let sl = getStageLength sw
        let cl = sl |> StageLength.toCeLength sw

        rp.WithProjectName(Some projectName)
          .WithRunFinished(Some false)
          .WithCeLength(Some cl)
          .WithStageLength(Some sl)
          .WithId (Some qp.Id)

    let paramMapRefiner (host: randomSorterBinsHost) (runParametersSeq: runParameters seq) : runParameters seq = 
        runParametersSeq |> Seq.choose (host.Filter >> Option.map enhancer)


    let project = project.create  projectName projectDesc 
                                     [| outputDataType.RunParameters; outputDataType.SorterEvalBins ""; outputDataType.SortingSet "EvenSampled"; outputDataType.SortingSet "HullSampled" |]

    let executor (host: randomSorterBinsHost) (runParameters: runParameters) 
                 (allowOverwrite: bool<allowOverwrite>) (cts: CancellationTokenSource) 
                 (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let repl = runParameters.GetRepl() |> Option.defaultValue (0 |> UMX.tag)
                report progress (sprintf "%s Starting Run %s" (MathUtils.getTimestampString()) %runId)

                let! (  sorterModelType, 
                        sortingWidth, 
                        stageLength, 
                        ceLength, 
                        sorterCount, 
                        sortableDataFormat) = host.ExtractDomainParams runParameters 
                                              |> Result.ofOption "Missing parameters"

                // 3. Create sorting set
                let sorterModelGen =
                    match sorterModelType with
                    | simpleSorterModelType.Msce -> msceRandGen.create rngFactory sortingWidth excludeSelfCe ceLength |> sorterModelGen.SmmMsceRandGen
                    | simpleSorterModelType.Mssi -> mssiRandGen.create rngFactory sortingWidth stageLength |> sorterModelGen.SmmMssiRandGen
                    | simpleSorterModelType.Msrs -> msrsRandGen.create rngFactory sortingWidth (OpsGenRatesArray.createUniform %stageLength) |> sorterModelGen.SmmMsrsRandGen
                    | simpleSorterModelType.Msuf4 -> msuf4RandGen.create rngFactory sortingWidth stageLength (Uf4GenRatesArray.createUniform %stageLength %sortingWidth) |> sorterModelGen.SmmMsuf4RandGen
                    | simpleSorterModelType.Msuf6 -> msuf6RandGen.create rngFactory sortingWidth stageLength (Uf6GenRatesArray.createUniform %stageLength %sortingWidth) |> sorterModelGen.SmmMsuf6RandGen
                    | _ -> failwith "Unsupported model type"

                let firstIdx = (%repl * %sorterCount) |> UMX.tag<sorterCount>
                let genSeg = sortingGenSegment.create (sorterModelGen |> sortingGen.Single) firstIdx sorterCount
                let qpFullSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "") 
                let fullSortingSet = genSeg.MakeSortingSet (%qpFullSet.Id |> UMX.tag)
                let fullSorterSet = fullSortingSet |> SortingSet.makeSorterSet

                // 4. Create tests
                let! _ = checkCancellation cts.Token
                let testModel = msasF.create sortingWidth |> sortableTestModel.MsasF
                let qpTests = makeQueryParamsFromRunParams runParameters (outputDataType.SortableTest "")
                let tests = SortableTestModel.makeSortableTest (%qpTests.Id |> UMX.tag) testModel sortableDataFormat

                // 5. Evaluate
                let qpEval = makeQueryParamsFromRunParams runParameters (outputDataType.SorterSetEval "")
                let eval = SorterSetEval.makeSorterSetEval (%qpEval.Id |> UMX.tag) fullSorterSet tests collectNewSortableTests

                // 6. Binning and Sampling
                let qpBins = makeQueryParamsFromRunParams runParameters (outputDataType.SorterEvalBins "")
                let bins = sorterEvalBins.create (%qpBins.Id |> UMX.tag) eval.SorterEvals

                let qpEven = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "EvenSampled")
                let evenSet = sortingSet.create (%qpEven.Id |> UMX.tag) (SortingSetFilter.sampleBinsEvenly samplesPerBin bins fullSortingSet)

                let qpHull = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "HullSampled")
                let hullSet = sortingSet.create (%qpHull.Id |> UMX.tag) (SortingSetFilter.sampleBinsConvexHull samplesPerBin bins fullSortingSet)

                // 7. Save
                //let! _ = host.ProjectDb.saveAsync qpBins (bins |> outputData.SorterEvalBins) allowOverwrite
                //let! _ = host.ProjectDb.saveAsync qpEven (evenSet |> outputData.SortingSet) allowOverwrite
                //let! _ = host.ProjectDb.saveAsync qpHull (hullSet |> outputData.SortingSet) allowOverwrite

                return runParameters.WithRunFinished (Some true)

            with e -> 
                return! Error (sprintf "Error in %s: %s" (runParameters |> RunParameters.getIdString) e.Message) |> async.Return
        }