namespace GeneSort.Project

open System
open System.Threading

open FSharp.UMX

open GeneSort.Core
open GeneSort.Sorter.Sortable
open GeneSort.Runs.Params
open GeneSort.Model.Sortable
open GeneSort.SortingOps
open GeneSort.Runs
open GeneSort.Db


module FullBoolEvals =

    let projectName = "FullBoolEvals" |> UMX.tag<projectName>
    let experimentDesc = "FullBoolEvals on RandomSorters with SortingWidth from 4 to 16 generated by Msce, Mssi, Msrs, and Msuf"
    let sorterSetSourceProjectName = "RandomSorters4to64" |> UMX.tag<projectName>


    let randomType = rngType.Lcg
    let sortableArrayType = sortableArrayType.Bools
  
    let sortingWidthValues = 
        [4; 6; 8; 12; 16;] |> List.map(fun d -> d.ToString())

    let sortingWidths() : string*string list =
        (runParameters.sortingWidthKey, sortingWidthValues)
        
    let sorterModelKeyValues() : string list =
        [ Some sorterModelKey.Mcse; 
          Some sorterModelKey.Mssi;
          Some sorterModelKey.Msrs; 
          Some sorterModelKey.Msuf4; 
          Some sorterModelKey.Msuf6; ]  |> List.map(SorterModelKey.toString)

    let sorterModelKeys() : string*string list =
        (runParameters.sorterModelTypeKey, sorterModelKeyValues() )


    let paramMapFilter (runParameters: runParameters) = 
        let sorterModelKey = runParameters.GetSorterModelKey().Value
        let sortingWidth = %runParameters.GetSortingWidth().Value
        let has3factor = (sortingWidth % 3 = 0)

        match sorterModelKey with
        | sorterModelKey.Mcse -> Some runParameters
        | sorterModelKey.Mssi -> Some runParameters
        | sorterModelKey.Msrs -> Some runParameters
        | sorterModelKey.Msuf4 ->
                if has3factor then None else
                Some runParameters
        | sorterModelKey.Msuf6 -> 
                if has3factor then Some runParameters else
                None


    let paramMapRefiner (runParametersSeq: runParameters seq) : runParameters seq = 
        let mutable index = 0

        let enhancer (runParameters : runParameters) : runParameters =
            runParameters.SetRunFinished false
            runParameters.SetProjectName projectName


            runParameters

        seq {
            for runParameters in runParametersSeq do
                    let filtrate = paramMapFilter runParameters
                    if filtrate.IsSome then
                        let retVal = enhancer filtrate.Value
                        retVal.SetIndex (UMX.tag<indexNumber> index)
                        yield filtrate.Value
                        index <- index + 1
        }


    let parameterSpans = 
        [ Project.repl1s(); sortingWidths(); sorterModelKeys();]

    let reportNames = [|"Bins"; "Profiles"; "Report3"; "Report4"|]

    let project = 
            Project.create 
                projectName
                experimentDesc
                reportNames
                parameterSpans
                paramMapRefiner


    let executor
            (db: IGeneSortDb)
            (runParameters: runParameters) 
            (cts: CancellationTokenSource) 
            (progress: IProgress<string> option) : Async<unit> =

        async {
            let index = runParameters.GetIndex().Value  
            let repl = runParameters.GetRepl().Value
            let sortingWidth = runParameters.GetSortingWidth().Value
        
            match progress with
            | Some p -> p.Report(sprintf "Executing Run %d_%d  %s" index %repl (runParameters.toString()))
            | None -> ()
        
            // Check cancellation before starting expensive operations
            cts.Token.ThrowIfCancellationRequested()

            let! allSourceRunParamsR = db.getAllProjectRunParametersAsync 
                                        sorterSetSourceProjectName 
                                        (Some cts.Token) 
                                        progress

            let allSourceRunParams = 
                match allSourceRunParamsR with
                | Ok rpA -> rpA
                | Error err -> failwith (sprintf "Error retrieving source run parameters from project %s: %s" 
                                                (sorterSetSourceProjectName |> UMX.untag<projectName>) err)

            let sourceRunParams =
                  RunParameters.pickByParameters 
                            allSourceRunParams 
                            [|runParameters.GetSorterModelKvp().Value; 
                              runParameters.GetReplKvp().Value; 
                              runParameters.GetSortingWidthKvp().Value |]
                  |> Option.defaultWith(fun () -> 
                        failwith (sprintf "No matching source run parameters found for Run %d_%d" index %repl))

            let queryParamsForSorterSet = queryParams.createFromRunParams (outputDataType.SorterSet None) sourceRunParams
            let sorterSet = db.loadAsync queryParamsForSorterSet
                            |> Async.RunSynchronously
                            |> function
                                | Ok (SorterSet ss) -> ss
                                | Ok _ -> failwith "Unexpected output data type: expected SorterSet"
                                | Error err -> failwith (sprintf "Error loading SorterSet: %s" err)


            let sorterTestModel = MsasF.create sortingWidth |> sortableTestModel.MsasF
            let sortableTests = SortableTestModel.makeSortableTests sorterTestModel sortableArrayType
            let sorterSetEval = SorterSetEval.makeSorterSetEval sorterSet sortableTests

            cts.Token.ThrowIfCancellationRequested()
            match progress with
            | Some p -> p.Report(sprintf "Run %d_%d: Saving sorterSet test results" index %repl)
            | None -> ()

            let queryParamsForSorterSetEval = queryParams.createFromRunParams (outputDataType.SorterSetEval None) runParameters
            do! db.saveAsync queryParamsForSorterSetEval (sorterSetEval |> outputData.SorterSetEval)

            // Mark run as finished
            runParameters.SetRunFinished true
        
            match progress with
            | Some p -> p.Report(sprintf "✓ Finished executing Run %d_%d" index %repl)
            | None -> ()
            }




