
namespace GeneSort.Project

open System
open System.IO

open FSharp.UMX
open MessagePack
open MessagePack.FSharp
open MessagePack.Resolvers

open GeneSort.Core
open GeneSort.Sorter
open GeneSort.Sorter.Sortable
open GeneSort.Project.Params
open GeneSort.Model.Sorter.Ce
open GeneSort.Model.Sorter.Si
open GeneSort.Model.Sorter.Uf4
open GeneSort.Model.Sorter.Rs


open GeneSort.Model.Sorter
open GeneSort.Model.Sortable
open GeneSort.SortingOps
open GeneSort.SortingResults
open GeneSort.SortingOps.Mp
open GeneSort.Model.Sorter.Uf6

module FullBoolTest = 

    let projectDir = "c:\Projects"

    let experimentName = "FullBoolTest"
    let experimentDesc = "FullBoolTest RandomSorters with SortingWidth from 4 to 16 generated by Msce, Mssi, Msrs, and Msuf"

    let randomType = rngType.Lcg
    let excludeSelfCe = true


    let getSorterCountForSortingWidth (factor:int) (sortingWidth: int<sortingWidth>) : int<sorterCount> =
        match %sortingWidth with
        | 4 -> (10 * factor) |> UMX.tag<sorterCount>
        | 6 -> (10 * factor) |> UMX.tag<sorterCount>
        | 8 -> (10 * factor) |> UMX.tag<sorterCount>
        | 12 -> (10 * factor) |> UMX.tag<sorterCount>
        | 16 -> (10 * factor) |> UMX.tag<sorterCount>
        | 24 -> (2 * factor) |> UMX.tag<sorterCount>
        | 32 -> (50 * factor) |> UMX.tag<sorterCount>
        | 48 -> (10 * factor) |> UMX.tag<sorterCount>
        | 64 -> (10 * factor) |> UMX.tag<sorterCount>
        | 96 -> (10 * factor) |> UMX.tag<sorterCount>
        | _ -> failwithf "Unsupported sorting width: %d" (%sortingWidth)


    let getStageLengthForSortingWidth (sortingWidth: int<sortingWidth>) : int<stageLength> =
        match %sortingWidth with
        | 4 -> 15 |> UMX.tag<stageLength>
        | 6 -> 20 |> UMX.tag<stageLength>
        | 8 -> 60 |> UMX.tag<stageLength>
        | 12 -> 80 |> UMX.tag<stageLength>
        | 16 -> 200 |> UMX.tag<stageLength>
        | 24 -> 400 |> UMX.tag<stageLength>
        | 32 -> 600 |> UMX.tag<stageLength>
        | 48 -> 2000 |> UMX.tag<stageLength>
        | 64 -> 4000 |> UMX.tag<stageLength>
        | 96 -> 10000 |> UMX.tag<stageLength>
        | _ -> failwithf "Unsupported sorting width: %d" (%sortingWidth)


    let sortableArrayType = sortableArrayType.Bools
  
    let sortingWidthValues = 
        [4; 6; 8; 12; 16; 24] |> List.map(fun d -> d.ToString())

    let sortingWidths() : string*string list =
        (runParameters.sortingWidthKey, sortingWidthValues)
        
    let sorterModelKeyValues () : string list =
        [ sorterModelKey.Mcse; 
          sorterModelKey.Mssi;
          sorterModelKey.Msrs; 
          sorterModelKey.Msuf4; 
          sorterModelKey.Msuf6; ]      |> List.map(SorterModelKey.toString)

    let sorterModelKeys () : string*string list =
        (runParameters.sorterModelTypeKey, sorterModelKeyValues() )

    let paramMapRefiner (runParameters: runParameters) = 
        let sorterModelKey = runParameters.GetSorterModelKey()
        let sortingWidth = %runParameters.GetSortingWidth()
        let has3factor = (sortingWidth % 3 = 0)

        match sorterModelKey with
        | sorterModelKey.Mcse -> Some runParameters
        | sorterModelKey.Mssi -> Some runParameters
        | sorterModelKey.Msrs -> Some runParameters
        | sorterModelKey.Msuf4 ->
                if has3factor then None else
                Some runParameters
        | sorterModelKey.Msuf6 -> 
                if has3factor then Some runParameters else
                None

    let parameterSet = 
        [ sortingWidths(); sorterModelKeys() ]

    let repls = [|"Rep1"; "Rep2"; "Rep3"; "Rep4"|]

    let workspace = 
            Workspace.create 
                experimentName 
                experimentDesc 
                projectDir
                repls 
                parameterSet 
                paramMapRefiner


    let executor (workspace: workspace) (repl: int<replNumber>) (run: run) : Async<unit> =
        async {

            Console.WriteLine(sprintf "Executing Run %d  Cycle %d  %s" run.Index %repl (run.RunParameters.toString()))
            run.RunParameters.SetRepl repl

            let sorterModelKey = run.RunParameters.GetSorterModelKey()
            let sortingWidth = run.RunParameters.GetSortingWidth()

            let stageLength = getStageLengthForSortingWidth sortingWidth
            run.RunParameters.SetStageLength stageLength

            let ceLength = (((float %stageLength) * (float %sortingWidth) * 0.6) |> int) |> UMX.tag<ceLength>
            run.RunParameters.SetCeLength ceLength


            let sorterModelMaker =
                match sorterModelKey with
                | sorterModelKey.Mcse -> (MsceRandGen.create randomType sortingWidth excludeSelfCe ceLength) |> sorterModelMaker.SmmMsceRandGen
                | sorterModelKey.Mssi -> (MssiRandGen.create randomType sortingWidth stageLength) |> sorterModelMaker.SmmMssiRandGen
                | sorterModelKey.Msrs -> 
                    let opsGenRatesArray = OpsGenRatesArray.createUniform %stageLength
                    (msrsRandGen.create randomType sortingWidth opsGenRatesArray) |> sorterModelMaker.SmmMsrsRandGen
                | sorterModelKey.Msuf4 -> 
                    let uf4GenRatesArray = Uf4GenRatesArray.createUniform %stageLength %sortingWidth
                    (msuf4RandGen.create randomType sortingWidth stageLength uf4GenRatesArray) |> sorterModelMaker.SmmMsuf4RandGen
                | sorterModelKey.Msuf6 -> 
                    let uf6GenRatesArray = Uf6GenRatesArray.createUniform %stageLength %sortingWidth
                    (msuf6RandGen.create randomType sortingWidth stageLength uf6GenRatesArray) |> sorterModelMaker.SmmMsuf6RandGen

            let replFactor = if (%repl = 0) then 1 else 10
            let sorterCount = sortingWidth |> getSorterCountForSortingWidth replFactor
            run.RunParameters.SetSorterCount sorterCount

            let firstIndex = (%repl * %sorterCount) |> UMX.tag<sorterCount>
            
            let sorterModelSetMaker = sorterModelSetMaker.create sorterModelMaker firstIndex sorterCount
            let sorterModelSet = sorterModelSetMaker.MakeSorterModelSet (Rando.create)
            let sorterSet = SorterModelSet.makeSorterSet sorterModelSet

            let sorterTestModel = MsasF.create sortingWidth |> sortableTestModel.MsasF
            let sorterTest = SortableTestModel.makeSortableTests sorterTestModel sortableArrayType
            let sorterSetEval = SorterSetEval.makeSorterSetEval sorterSet sorterTest

            do! OutputData.saveToFileO workspace.WorkspaceFolder run.Index run.Repl (sorterSet |> outputData.SorterSet)
            do! OutputData.saveToFileO workspace.WorkspaceFolder run.Index run.Repl (sorterSetEval |> outputData.SorterSetEval)
            do! OutputData.saveToFileO workspace.WorkspaceFolder run.Index run.Repl (sorterModelSetMaker |> outputData.SorterModelSetMaker)

            Console.WriteLine(sprintf "Finished executing Run %d  Cycle  %d \n" run.Index %repl)
        }


    // Executor to generate a report for each SorterTest across all SorterTestSets, one line per SorterTest
    let binReportExecutor (workspace: workspace) =
            try
                Console.WriteLine(sprintf "Generating SorterEval report in workspace %s"  workspace.WorkspaceFolder)
                let sorterSetEvalSamplesFolder = OutputData.getOutputDataFolder workspace outputDataType.SorterSetEval
                if not (Directory.Exists sorterSetEvalSamplesFolder) then
                    failwith (sprintf "Output folder %s does not exist" sorterSetEvalSamplesFolder)

                // Find all .msgpack files in the output folder
                let files = Directory.GetFiles(sorterSetEvalSamplesFolder, "*.msgpack")

                // Initialize the MessagePack resolver
                let resolver = CompositeResolver.Create(FSharpResolver.Instance, StandardResolver.Instance)
                let options = MessagePackSerializerOptions.Standard.WithResolver(resolver)


                // Process each file and collect data for each SorterTest
                let summaries : (string*string*string*string*string*string) list =
                    files
                    |> Seq.map (
                        fun ssEvalPath ->
                            try
                                use ssEvalStream = new FileStream(ssEvalPath, FileMode.Open, FileAccess.Read, FileShare.Read)
                                let ssEvalDto = MessagePackSerializer.Deserialize<sorterSetEvalDto>(ssEvalStream, options)
                                let sorterSetEval = SorterSetEvalDto.toDomain ssEvalDto          
                                let sorterSetEvalBins = SorterSetEvalBins.create 1 sorterSetEval

                                let runParams = OutputData.getRunParametersForOutputDataPath ssEvalPath
                                let sorterModelKey = runParams.GetSorterModelKey() |> SorterModelKey.toString
                                let swFull = (%runParams.GetSortingWidth()).ToString()

                                let prpt = SorterSetEvalBins.getBinCountReport sorterSetEvalBins
                                let appended = prpt |> Array.map(fun aa -> (swFull, sorterModelKey, aa.[0], aa.[1], aa.[2], aa.[3]))
                                appended
                            with e ->
                                failwith (sprintf "Error processing file %s: %s" ssEvalPath e.Message)
                    )
                    
                    |> Array.concat
                    |> Seq.toList


                // Generate the Markdown report, one line per SorterTest
                let reportContent =
                    [ "# sorterEval Report"
                      sprintf "Generated on %s" (DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"))
                      sprintf "Workspace: %s" workspace.WorkspaceFolder
                      ""
                      "Sorting Width\t SorterModel\t ceLength\t stageLength\t binCount\t unsortedReport"
                    ]
                    @ (summaries
                       |> List.map (
                            fun (sortingWidth, sorterModelKey, ceLength, stageLength, binCount, unsortedReport) ->
                                    sprintf "%s \t %s \t %s \t %s \t %s \t %s " sortingWidth sorterModelKey ceLength stageLength binCount unsortedReport))
                    |> String.concat "\n"


                // Save the report to a file
                let reportFilePath = Path.Combine(workspace.WorkspaceFolder, sprintf "%s_SorterEvalReport_%s.txt" "SorterSetEvalSamples" (DateTime.Now.ToString("yyyyMMdd_HHmmss")))
                File.WriteAllText(reportFilePath, reportContent)

                Console.WriteLine(sprintf "SorterTest count report saved to %s" reportFilePath)
            with ex ->
                Console.WriteLine(sprintf "Error generating SorterTest count report for %s: %s" "SorterTestSet" ex.Message)
                raise ex



    // Executor to generate a report for each SorterTest across all SorterTestSets, one line per SorterTest
    let ceUseProfileReportExecutor (workspace: workspace) =
            try
                let binCount = 20
                let blockGrowthRate = 1.2
                Console.WriteLine(sprintf "Generating Ce Profile report in workspace %s"  workspace.WorkspaceFolder)
                let sorterSetEvalSamplesFolder = OutputData.getOutputDataFolder workspace outputDataType.SorterSetEval
                if not (Directory.Exists sorterSetEvalSamplesFolder) then
                    failwith (sprintf "Output folder %s does not exist" sorterSetEvalSamplesFolder)

                // Find all .msgpack files in the output folder
                let files = Directory.GetFiles(sorterSetEvalSamplesFolder, "*.msgpack")

                // Initialize the MessagePack resolver
                let resolver = CompositeResolver.Create(FSharpResolver.Instance, StandardResolver.Instance)
                let options = MessagePackSerializerOptions.Standard.WithResolver(resolver)
                
                let summaries : string list =
                    files
                    |> Seq.map (
                        fun ssEvalPath ->
                            try
                                use ssEvalStream = new FileStream(ssEvalPath, FileMode.Open, FileAccess.Read, FileShare.Read)
                                let ssEvalDto = MessagePackSerializer.Deserialize<sorterSetEvalDto>(ssEvalStream, options)
                                let sorterSetEval = SorterSetEvalDto.toDomain ssEvalDto     
                                let sorterSetCeUseProfile = SorterSetCeUseProfile.makeSorterSetCeUseProfile binCount blockGrowthRate sorterSetEval
  
                                let runParams = OutputData.getRunParametersForOutputDataPath ssEvalPath
                                let sorterModelKey =   runParams.GetSorterModelKey() 
                                let swFull = runParams.GetSortingWidth() 

                                let linePrefix = sprintf "%s \t %s" (%swFull.ToString()) (sorterModelKey |> SorterModelKey.toString)
                                SorterSetCeUseProfile.makeCsvLines linePrefix sorterSetCeUseProfile
                            with e ->
                                failwith (sprintf "Error processing file %s: %s" ssEvalPath e.Message)
                    )
                    |> Array.concat
                    |> Seq.toList

                // Generate the Markdown report, one line per SorterTest
                let reportContent =
                    [ "# sorterCeProfile Report"
                      sprintf "Generated on %s" (DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"))
                      sprintf "Workspace: %s" workspace.WorkspaceFolder
                      ""
                      "Sorting Width\t SorterModel\t lastCe"
                    ]
                    @ summaries
                    |> String.concat "\n"


                // Save the report to a file
                let reportFilePath = Path.Combine(workspace.WorkspaceFolder, sprintf "SorterCeUseReport_%s.txt" (DateTime.Now.ToString("yyyyMMdd_HHmmss")))
                File.WriteAllText(reportFilePath, reportContent)

                Console.WriteLine(sprintf "Ce Profile report saved to %s" reportFilePath)
            with ex ->
                Console.WriteLine(sprintf "Error generating Ce Profile report for %s: %s" "SorterTestSet" ex.Message)
                raise ex



    let RunAll() =
        for i in 0 .. 4 do
            let repl = i |> UMX.tag<replNumber>
            WorkspaceOps.executeWorkspace workspace repl 12 executor


    let RunSorterEvalReport() =
    //     (binReportExecutor workspace)
       (ceUseProfileReportExecutor workspace)









