namespace GeneSort.Project

open System
open System.Threading
open FSharp.UMX
open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Runs
open GeneSort.Db
open GeneSort.SortingOps
open GeneSort.Model.Sorting
open GeneSort.FileDb
open OpsUtils
open GeneSort.SortingResults

/// Host type for MergeIntEvals to swap between Testing (P1) and Production (P2)
type mergeIntEvalsHost = 
    private { 
        _projectDb: IGeneSortDb 
        _parameterSpans: (string * string list) list
        _filter: runParameters -> runParameters option
    }
    static member Create db spans filter =
        { _projectDb = db; _parameterSpans = spans; _filter = filter }

    member this.ProjectDb = this._projectDb
    member this.ParameterSpans = this._parameterSpans
    member this.Filter = this._filter

    member this.ExtractDomainParams (rp: runParameters) =
        maybe {
            let! r = rp.GetRepl()
            let! sw = rp.GetSortingWidth()
            let! sdf = rp.GetSortableDataFormat()
            let! md = rp.GetMergeDimension()
            let! mst = rp.GetMergeSuffixType()
            let! smt = rp.GetSorterModelType()
            return (r, sw, md, mst, sdf, smt)
        }


module MergeIntEvals =

    let projectName = "MergeIntEvals" |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\MergeIntEvals\\Data" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "MergeIntEvals on RandomSorters with SortingWidth from 16 to 64 generated by Msce, Mssi, Msrs, and Msuf"

    // --- Shared Filtering Logic ---

    let private sorterModelTypeForSortingWidth (rp: runParameters) =
        let sorterModelKey = rp.GetSorterModelType().Value
        let sortingWidth = rp.GetSortingWidth().Value
        let has2factor = (%sortingWidth % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sortingWidth)
        let isMuf6able = (%sortingWidth % 3 = 0) && (MathUtils.isAPowerOfTwo (%sortingWidth / 3))

        match sorterModelKey with
        | sorterModelType.Msce -> Some rp
        | sorterModelType.Mssi | sorterModelType.Msrs -> if has2factor then Some rp else None
        | sorterModelType.Msuf4 -> if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> if isMuf6able then Some rp else None
        | _ -> None
          
    let private mergeDimensionDividesSortingWidth (rp: runParameters) =
        let sw = rp.GetSortingWidth().Value
        let md = rp.GetMergeDimension().Value
        if (%sw % %md = 0) then Some rp else None
            
    let private limitForMergeFillType (rp: runParameters) =
        let ft = rp.GetMergeSuffixType().Value
        let md = rp.GetMergeDimension().Value
        if (ft.IsNoSuffix && %md > 4) then None else Some rp

    let paramMapFilter (rp: runParameters) = 
        Some rp
        |> Option.bind sorterModelTypeForSortingWidth
        |> Option.bind limitForMergeFillType
        |> Option.bind mergeDimensionDividesSortingWidth

    // --- Configuration P1 (Testing) ---

    module P1 =
        let spans = [
            (runParameters.sortingWidthKey, ["16"])
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce] |> List.map SorterModelType.toString)
            (runParameters.sortableDataFormatKey, [sortableDataFormat.Int8Vector512] |> List.map SortableDataFormat.toString)
            (runParameters.mergeDimensionKey, ["2"; "4"])
            (runParameters.mergeSuffixTypeKey, [mergeSuffixType.NoSuffix] |> List.map MergeSuffixType.toString)
        ]
        let host = mergeIntEvalsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    // --- Configuration P2 (Production) ---

    module P2 =
        let spans = [
            (runParameters.sortingWidthKey, [16; 128; 256] |> List.map string)
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce; sorterModelType.Mssi; sorterModelType.Msrs; sorterModelType.Msuf4] |> List.map SorterModelType.toString)
            (runParameters.sortableDataFormatKey, [sortableDataFormat.Int8Vector512] |> List.map SortableDataFormat.toString)
            (runParameters.mergeDimensionKey, [2; 4; 8] |> List.map string)
            (runParameters.mergeSuffixTypeKey, [mergeSuffixType.NoSuffix; mergeSuffixType.VV_1] |> List.map MergeSuffixType.toString)
        ]
        let host = mergeIntEvalsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    // --- Helpers ---

    let makeQueryParams repl outputDataType sortingWidth sorterModelType sortableDataFormat mergeDimension mergeFillType =
        queryParams.create (Some projectName) repl outputDataType
            [| (runParameters.sortingWidthKey, sortingWidth |> UmxExt.intToString); 
               (runParameters.sorterModelTypeKey, sorterModelType |> Option.map SorterModelType.toString |> UmxExt.stringToString);
               (runParameters.mergeDimensionKey, mergeDimension |> UmxExt.intToString);
               (runParameters.mergeSuffixTypeKey, mergeFillType |> Option.map MergeSuffixType.toString |> UmxExt.stringToString); |]

    let makeQueryParamsFromRunParams (runParams: runParameters) (outputDataType: outputDataType) =
        makeQueryParams (runParams.GetRepl()) outputDataType (runParams.GetSortingWidth()) 
                        (runParams.GetSorterModelType()) (runParams.GetSortableDataFormat()) 
                        (runParams.GetMergeDimension()) (runParams.GetMergeSuffixType())

    let enhancer (rp : runParameters) : runParameters =
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        rp.WithProjectName(Some projectName).WithRunFinished(Some false).WithId (Some qp.Id)

    let paramMapRefiner (host: mergeIntEvalsHost) (runParametersSeq: runParameters seq) : runParameters seq = 
        runParametersSeq 
        |> Seq.choose (host.Filter >> Option.map enhancer)
        |> Seq.toArray
        |> Array.toSeq

    let outputDataTypes = 
        [| outputDataType.RunParameters; outputDataType.SorterSetEval "";
           outputDataType.TextReport ("Bins" |> UMX.tag); outputDataType.TextReport ("Profiles" |> UMX.tag) |]
     
    let project = project.create  projectName projectDesc outputDataTypes


    // --- The Executor ---

    let executor (host: mergeIntEvalsHost) (runParameters: runParameters) 
                 (allowOverwrite: bool<allowOverwrite>) (cts: CancellationTokenSource) 
                 (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                let startTime = DateTime.Now
                let! (_: unit) = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                report progress (sprintf "%s Starting Run %s" (MathUtils.getTimestampString()) runId)

                // 2. Safe Param Extraction (Via Host)
                let! (repl, sw, md, mst, sdf, smt) = 
                    host.ExtractDomainParams runParameters |> Result.ofOption "Missing domain parameters"

                // 3. Load Sortable Tests
                let qpSortableTests = SortableMergeTests.makeQueryParams 
                                        (Some (0 |> UMX.tag)) (Some sw) (Some md) (Some mst) (Some sdf) (outputDataType.SortableTest "")
                let dbSortableTests = new GeneSortDbMp(SortableMergeTests.projectFolder) :> IGeneSortDb
                let! rawTestData = dbSortableTests.loadAsync qpSortableTests 
                let! sortableTest = rawTestData |> OutputData.asSortableTest

                // 4. Load SortingSet
                let qpSorterModelSet = RandomSorters.makeQueryParams (Some repl) (Some sw) (Some smt) (outputDataType.SortingSet "")
                let dbRandomSorters = new GeneSortDbMp(RandomSorters.projectFolder) :> IGeneSortDb
                let! smsOutput = dbRandomSorters.loadAsync qpSorterModelSet
                let! sortingSet = smsOutput |> OutputData.asSortingSet

                // 5. Computation
                let sorterSet = SortingSet.makeSorterSet sortingSet
                let! (_: unit) = checkCancellation cts.Token
                let qpEval = makeQueryParamsFromRunParams runParameters (outputDataType.SorterSetEval "")
                let sorterSetEval = SorterSetEval.makeSorterSetEval (%qpEval.Id |> UMX.tag) sorterSet sortableTest false

                // 6. Save
                let! (_: unit) = host.ProjectDb.saveAsync qpEval (sorterSetEval |> outputData.SorterSetEval) allowOverwrite

                let qpPass = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "Pass")
                let passSet = SortingEval.makePassingSortingSet (%qpPass.Id |> UMX.tag) sortingSet sorterSetEval
                let! (_: unit) = host.ProjectDb.saveAsync qpPass (passSet |> outputData.SortingSet) allowOverwrite
                // 7. Success
                let duration = DateTime.Now - startTime
                return (runParameters.WithRunFinished (Some true)).WithElapsedTime (Some (duration.TotalSeconds.ToString()))

            with (e: exn) ->
                let runId = runParameters |> RunParameters.getIdString
                return! Error (sprintf "Fatal error in Run %s: %s" runId e.Message) |> async.Return
        }