namespace GeneSort.Project

open FSharp.UMX
open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Runs
open GeneSort.Db
open GeneSort.FileDb
open GeneSort.Model.Sorting
open GeneSort.Model.Sorting.Sorter.Ce
open GeneSort.Model.Sorting.Sorter.Si
open GeneSort.Model.Sorting.Sorter.Rs
open GeneSort.Model.Sorting.Sorter.Uf4
open GeneSort.Model.Sorting.Sorter.Uf6
open System
open System.Threading

type randomSortersHost = 
    private { 
        _projectDb: IGeneSortDb 
        _parameterSpans: (string * string list) list
        _filter: runParameters -> runParameters option
    }
    static member Create db spans filter =
        { _projectDb = db; _parameterSpans = spans; _filter = filter }

    member this.ProjectDb = this._projectDb
    member this.ParameterSpans = this._parameterSpans
    member this.Filter = this._filter

    /// Logic for calculating lengths based on model and width
    member this.GetStageLength (smt: sorterModelType) (sw: int<sortingWidth>) : int<stageLength> =
        match %sw with
        | 4 -> 5 |> UMX.tag
        | 6 -> 20 |> UMX.tag
        | 8 -> 40 |> UMX.tag
        | 12 -> 80 |> UMX.tag
        | 16 -> 100 |> UMX.tag
        | 18 -> 120 |> UMX.tag
        | 20 -> 130 |> UMX.tag
        | 22 -> 140 |> UMX.tag
        | 24 -> 200 |> UMX.tag
        | 32 -> 
            match smt with
            | sorterModelType.Msuf4 -> 600 |> UMX.tag
            | _ -> 300 |> UMX.tag
        | 64 -> 
            match smt with
            | sorterModelType.Msuf4 -> 2000 |> UMX.tag
            | sorterModelType.Msrs -> 800 |> UMX.tag
            | _ -> 600 |> UMX.tag
        | 128 -> 
            match smt with
            | sorterModelType.Msuf4 -> 4000 |> UMX.tag
            | sorterModelType.Msrs -> 1800 |> UMX.tag
            | sorterModelType.Mssi -> 1500 |> UMX.tag
            | _ -> 1200 |> UMX.tag
        | 256 -> 
            match smt with
            | sorterModelType.Msuf4 -> 6000 |> UMX.tag
            | sorterModelType.Msrs -> 4000 |> UMX.tag
            | _ -> 3000 |> UMX.tag
        | _ -> failwithf "Unsupported sorting width: %d" (%sw)

    /// Centralized safe parameter extraction
    member this.ExtractDomainParams (rp: runParameters) =
        maybe {
            let! smk = rp.GetSorterModelType()
            let! sw = rp.GetSortingWidth()
            let! sl = rp.GetStageLength()
            let! cl = rp.GetCeLength()
            let! sc = rp.GetSorterCount()
            return (smk, sw, sl, cl, sc)
        }

module RandomSorters =
    // --- Project Constants ---
    let projectName = "RandomSorters" |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomSorters\\Data" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "RandomSorters, generated by Msce, Mssi, Msrs, and Msuf"
    let rngFactory = rngFactory.LcgFactory
    let excludeSelfCe = true

    // --- Shared Filtering Logic ---
    let private sorterModelTypeForSortingWidth (rp: runParameters) =
        let smt = rp.GetSorterModelType().Value
        let sw = rp.GetSortingWidth().Value
        let has2factor = (%sw % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sw)
        let isMuf6able = (%sw % 3 = 0) && (MathUtils.isAPowerOfTwo (%sw / 3))

        match smt with
        | sorterModelType.Msce -> Some rp
        | sorterModelType.Mssi | sorterModelType.Msrs -> if has2factor then Some rp else None
        | sorterModelType.Msuf4 -> if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> if isMuf6able then Some rp else None
        | _ -> None

    let paramMapFilter (rp: runParameters) = 
        Some rp |> Option.bind sorterModelTypeForSortingWidth

    // --- Configuration P1 (Testing) ---
    module P1 =
        let spans = [ 
            (runParameters.sortingWidthKey, ["16"])
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce] |> List.map SorterModelType.toString)
        ]
        let host = randomSortersHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    // --- Configuration P2 (Production) ---
    module P2 =
        let spans = [ 
            (runParameters.sortingWidthKey, ["16"; "32"; "64"; "128"; "256"])
            (runParameters.sorterModelTypeKey, 
                [sorterModelType.Msce; sorterModelType.Mssi; sorterModelType.Msrs; sorterModelType.Msuf4] 
                |> List.map SorterModelType.toString)
        ]
        let host = randomSortersHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    // --- Query Parameter Helpers ---
    let makeQueryParams (repl: int<replNumber> option) (sortingWidth:int<sortingWidth> option)
                        (sorterModelType:sorterModelType option) (outputDataType: outputDataType) =
        queryParams.create (Some projectName) repl outputDataType
            [| (runParameters.sortingWidthKey, sortingWidth |> SortingWidth.toString); 
               (runParameters.sorterModelTypeKey, sorterModelType |> Option.map SorterModelType.toString |> UmxExt.stringToString) |]

    let makeQueryParamsFromRunParams (runParams: runParameters) (outputDataType: outputDataType) =
        makeQueryParams (runParams.GetRepl()) (runParams.GetSortingWidth())
                        (runParams.GetSorterModelType()) outputDataType

    // --- Refinement ---
    let enhancer (host: randomSortersHost) (rp : runParameters) : runParameters =
        let sw = rp.GetSortingWidth().Value
        let smt = rp.GetSorterModelType().Value
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        let stageLength = host.GetStageLength smt sw
        let ceLength = stageLength |> StageLength.toCeLength sw
        let sorterCount = 100 |> UMX.tag<sorterCount>

        rp.WithProjectName(Some projectName)
          .WithRunFinished(Some false)
          .WithCeLength(Some ceLength)
          .WithStageLength(Some stageLength)
          .WithSorterCount(Some sorterCount)


    let paramMapRefiner (host: randomSortersHost) (runParametersSeq: runParameters seq) : runParameters seq = 
            runParametersSeq 
            |> Seq.choose host.Filter 
            |> Seq.map (enhancer host)
            |> Seq.toArray
            |> Array.toSeq

    // --- Helper for Model Generation ---
    let private getModelGen (smt: sorterModelType) sw sl cl =
        match smt with
        | sorterModelType.Msce -> 
            msceRandGen.create rngFactory sw excludeSelfCe cl |> sorterModelGen.SmmMsceRandGen
        | sorterModelType.Mssi -> 
            mssiRandGen.create rngFactory sw sl |> sorterModelGen.SmmMssiRandGen
        | sorterModelType.Msrs -> 
            let rates = OpsGenRatesArray.createUniform %sl
            msrsRandGen.create rngFactory sw rates |> sorterModelGen.SmmMsrsRandGen
        | sorterModelType.Msuf4 -> 
            let rates = Uf4GenRatesArray.createUniform %sl %sw
            msuf4RandGen.create rngFactory sw sl rates |> sorterModelGen.SmmMsuf4RandGen
        | sorterModelType.Msuf6 -> 
            let rates = Uf6GenRatesArray.createUniform %sl %sw
            msuf6RandGen.create rngFactory sw sl rates |> sorterModelGen.SmmMsuf6RandGen

    let outputDataTypes = 
        [| outputDataType.RunParameters; outputDataType.SorterModelSetGen ""; outputDataType.SorterSet "";
           outputDataType.TextReport ("Bins" |> UMX.tag); outputDataType.TextReport ("Profiles" |> UMX.tag) |]

    let project = 
        project.create projectName projectDesc outputDataTypes

    // --- The Executor ---
    let executor (host: randomSortersHost) (db: IGeneSortDb) (runParameters: runParameters) 
                 (allowOverwrite: bool<allowOverwrite>) (cts: CancellationTokenSource) 
                 (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let repl = runParameters.GetRepl() |> Option.defaultValue (-1 |> UMX.tag)
                ProjectOps.report progress (sprintf "%s Starting Random Generation %s repl %d" (MathUtils.getTimestampString()) %runId %repl)

                // 2. Safe Parameter Extraction (Via Host)
                let! (smt, sw, sl, cl, sc) = 
                    host.ExtractDomainParams runParameters 
                    |> Result.ofOption (sprintf "Run %s: Missing required parameters" %runId)

                // 3. Create sorting set
                let sorterModelGen = getModelGen smt sw sl cl
                let firstIndex = (%repl * %sc) |> UMX.tag<sorterCount>
                
                let sortingSetGen = sortingGenSegment.create (sorterModelGen |> sortingGen.Single) firstIndex sc
                let qpSortingSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "") 
                let sortingSet = sortingSetGen.MakeSortingSet (%qpSortingSet.Id |> UMX.tag) 

                // 4. Save (Using the host's DB connection)
                let! _ = host.ProjectDb.saveAsync qpSortingSet (sortingSet |> outputData.SortingSet) allowOverwrite
            
                ProjectOps.report progress (sprintf "Saved SortingSet %s for run: %s" (%qpSortingSet.Id.ToString()) %runId)

                return runParameters.WithRunFinished (Some true)

            with e -> 
                return! Error (sprintf "Unexpected error in run %s: %s" 
                        (runParameters |> RunParameters.getIdString) e.Message) 
                        |> async.Return
        }