namespace GeneSort.Project.SorterBins

open System
open System.Threading
open FSharp.UMX
open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Runs
open GeneSort.Db
open GeneSort.Model.Sorting
open GeneSort.SortingOps
open GeneSort.SortingResults
open GeneSort.SortingResults.Bins
open GeneSort.Project
open GeneSort.FileDb
open GeneSort.Project.OpsUtils

/// Host type for MergeRandomSorterBins to manage environment-specific spans and filtering
type mergeRandomSorterBinsHost = 
    private { 
        _projectDb: IGeneSortDb 
        _parameterSpans: (string * string list) list
        _filter: runParameters -> runParameters option
        _maxSampledSetSize: int
    }
    static member Create db spans filter maxSampledSetSize =
        { _projectDb = db; _parameterSpans = spans; _filter = filter; _maxSampledSetSize = maxSampledSetSize }

    member this.ProjectDb = this._projectDb
    member this.ParameterSpans = this._parameterSpans
    member this.Filter = this._filter
    member this.MaxSampledSetSize = this._maxSampledSetSize
    member this.ExtractDomainParams (rp: runParameters) =
        maybe {
            let! smt = rp.GetSorterModelType()
            let! sw = rp.GetSortingWidth()
            let! srp = rp.GetStartingRepl()
            let! rsp = rp.GetReplSpan()
            return (smt, sw, srp, rsp)
        }

module MergeRandomSorterBins =

    let projectName = "MergeRandomSorterBins" |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomSorterBins\\Merge\\Data" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "Merge RandomSorterBins, generated by Msce, Mssi, Msrs, and Msuf"
    
    let samplesPerBin = 1
    let excludeSelfCe = true
    let allowOverwrite = false |> UMX.tag<allowOverwrite>

    // --- Helpers ---

    let private sorterModelTypeForSortingWidth (rp: runParameters) =
        let smt = rp.GetSorterModelType().Value
        let sw = rp.GetSortingWidth().Value
        let has2factor = (%sw % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sw)
        let isMuf6able = (%sw % 3 = 0) && (MathUtils.isAPowerOfTwo (%sw / 3))

        match smt with
        | sorterModelType.Msce -> Some rp
        | sorterModelType.Mssi | sorterModelType.Msrs -> if has2factor then Some rp else None
        | sorterModelType.Msuf4 -> if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> if isMuf6able then Some rp else None
        | _ -> None

    let paramMapFilter (rp: runParameters) = 
        Some rp |> Option.bind sorterModelTypeForSortingWidth

    // --- Configurations ---

    module P1 =
        let maxSampledSetSize = 200
        let spans = [
            (runParameters.sortingWidthKey, [16;] |> List.map string)
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce] |> List.map SorterModelType.toString)
            (runParameters.startingReplKey, ["0"])
            (runParameters.replSpanKey, ["10"])
        ]
        let host = mergeRandomSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter maxSampledSetSize

    module P2 =
        let maxSampledSetSize = 500
        let spans = [
            (runParameters.sortingWidthKey, [16;] |> List.map string)
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce; sorterModelType.Mssi; sorterModelType.Msrs; sorterModelType.Msuf4; sorterModelType.Msuf6] |> List.map SorterModelType.toString)
            (runParameters.startingReplKey, ["0"])
            (runParameters.replSpanKey, ["10"])
        ]
        let host = mergeRandomSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter  maxSampledSetSize

    // --- Query logic ---

    let makeQueryParams repl startingRepl replSpan sw smt outputDataType =
        queryParams.create (Some projectName) repl outputDataType
            [| (runParameters.sortingWidthKey, sw |> SortingWidth.toString) 
               (runParameters.sorterModelTypeKey, smt |> Option.map SorterModelType.toString |> UmxExt.stringToString)
               (runParameters.startingReplKey, startingRepl |> UmxExt.intToString)
               (runParameters.replSpanKey, replSpan |> UmxExt.intToString) |]

    let makeQueryParamsFromRunParams (rp: runParameters) (odt: outputDataType) =
        makeQueryParams (rp.GetRepl()) (rp.GetStartingRepl()) (rp.GetReplSpan()) (rp.GetSortingWidth()) (rp.GetSorterModelType()) odt

    let enhancer (rp : runParameters) : runParameters =
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        rp.WithProjectName(Some projectName)
          .WithRunFinished(Some false)
          .WithId (Some qp.Id)

    let paramMapRefiner (host: mergeRandomSorterBinsHost) (runParametersSeq: runParameters seq) : runParameters seq = 
        runParametersSeq |> Seq.choose (host.Filter >> Option.map enhancer)


    let project = project.create  projectName projectDesc 
                    [| outputDataType.RunParameters; 
                       outputDataType.SorterEvalBins ""; 
                       outputDataType.SortingSet "EvenSampled"; 
                       outputDataType.SortingSet "HullSampled"; 
                       outputDataType.SortingSet "CenterSampled"; 
                       outputDataType.SortingSet "WinningSampled";
                       outputDataType.TextReport ("MergeReport" |> UMX.tag) |]

    // --- Executor ---

    let executor (host: mergeRandomSorterBinsHost) (runParameters: runParameters) 
                 (allowOverwrite: bool<allowOverwrite>) (cts: CancellationTokenSource) 
                 (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let! (sorterModelType, sortingWidth, srp, rsp) = host.ExtractDomainParams runParameters |> Result.ofOption "Missing parameters"
                
                report progress (sprintf "Merging %d repls starting at %d for %s" %rsp %srp %runId)

                // 1. Output Query Params
                let qpBins = makeQueryParamsFromRunParams runParameters (outputDataType.SorterEvalBins "")
                let qpEven = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "EvenSampled")
                let qpHull = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "HullSampled")
                let qpCenter = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "CenterSampled")
                let qpWinning = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "WinningSampled")

                // 2. Initialize Merged Containers
                let mutable mBins = sorterEvalBins.createEmpty (%qpBins.Id |> UMX.tag)
                let mutable mEven = sortingSet.create (%qpEven.Id |> UMX.tag) [||]
                let mutable mCenter = sortingSet.create (%qpCenter.Id |> UMX.tag) [||]
                let mutable mWinning = sortingSet.create (%qpWinning.Id |> UMX.tag) [||]

                let dbSource = new GeneSortDbMp(RandomSorterBins.projectFolder) :> IGeneSortDb

                // 3. Merging Loop
                for r in 0 .. (%rsp - 1) do
                    let currentRepl = %srp + r |> UMX.tag<replNumber>
                    
                    let qpSrcBins = RandomSorterBins.makeQueryParams 
                                            (Some currentRepl) 
                                            (Some sortingWidth) 
                                            (Some sorterModelType) 
                                            (outputDataType.SorterEvalBins "")
                    let! srcBins = dbSource.loadAsync qpSrcBins |> AsyncResult.bindResult OutputData.asSorterEvalBins

                    let qpSrcSet = RandomSorterBins.makeQueryParams 
                                            (Some currentRepl) 
                                            (Some sortingWidth) 
                                            (Some sorterModelType) 
                                            (outputDataType.SortingSet "EvenSampled")
                    let! srcSet = dbSource.loadAsync qpSrcSet |> AsyncResult.bindResult OutputData.asSortingSet

                    // Update Aggregates
                    mEven <- SortingSet.merge mEven srcSet
                    mCenter <- SortingSet.merge mCenter srcSet
                    mWinning <- SortingSet.merge mWinning srcSet
                    mBins <- SorterEvalBins.merge mBins srcBins

                    // Incremental Down-sampling to keep memory footprint stable
                    mEven <- sortingSet.create mEven.Id (SortingSetFilter.sampleBinsEvenly samplesPerBin mBins mEven)
                    mCenter <- sortingSet.create mCenter.Id (SortingSetFilter.sampleTheCenterBins host.MaxSampledSetSize mBins mCenter)
                    mWinning <- sortingSet.create mWinning.Id (SortingSetFilter.sampleWinningBins host.MaxSampledSetSize mBins mWinning)

                // 4. Final Sampling for Hull
                let hullSet = sortingSet.create (%qpHull.Id |> UMX.tag) (SortingSetFilter.sampleBinsConvexHull samplesPerBin mBins mEven)

                // 5. Reporting
                let reportName = $"MergeReport_{%sortingWidth}_{sorterModelType |> SorterModelType.toString}" |> UMX.tag<textReportName>
                let qpReport = makeQueryParamsFromRunParams runParameters (outputDataType.TextReport reportName)
                

                let keyFormatter ((sw:int<sortingWidth>, smt:sorterModelType), key: sorterEvalKey) = 
                            sprintf "%d_%s_%s" 
                                    %sw 
                                    (smt |> SorterModelType.toString) 
                                    (key.AsString())

                let tableMap = SorterEvalBins.getPropertyMaps 
                                    mBins 
                                    (sortingWidth, sorterModelType) 
                                    Map.empty 
                               |> Map.ofSeq

                let headers, rows = DataTableReport.mapToTabDelimitedStrings keyFormatter tableMap
                let dtReport = DataTableReport.create %reportName headers
                dtReport.AppendDataRows (rows |> Array.toSeq)

                // 6. Save results
                let! _ = host.ProjectDb.saveAsync qpBins (mBins |> outputData.SorterEvalBins) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpEven (mEven |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpHull (hullSet |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpCenter (mCenter |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpWinning (mWinning |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpReport (dtReport |> outputData.TextReport) allowOverwrite

                return runParameters.WithRunFinished (Some true)

            with e -> 
                return! Error (sprintf "Merge failure for %s: %s" (runParameters |> RunParameters.getIdString) e.Message) |> async.Return
        }