namespace GeneSort.Project

open FSharp.UMX
open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Runs
open GeneSort.Db
open GeneSort.FileDb
open GeneSort.Model.Sorting
open GeneSort.SortingResults
open GeneSort.SortingResults.Bins
open GeneSort.Project
open System
open System.Threading
open GeneSort.Project.SorterBins
open GeneSort.SortingOps

type mergeRandomMergeSorterBinsHost = 
    private { 
        _projectDb: IGeneSortDb 
        _parameterSpans: (string * string list) list
        _filter: runParameters -> runParameters option
    }
    static member Create db spans filter =
        { _projectDb = db; _parameterSpans = spans; _filter = filter }

    member this.ProjectDb = this._projectDb
    member this.ParameterSpans = this._parameterSpans
    member this.Filter = this._filter

    member this.ExtractDomainParams (rp: runParameters) =
        maybe {
            let! md = rp.GetMergeDimension()
            let! mst = rp.GetMergeSuffixType()
            let! smt = rp.GetSorterModelType()
            let! sw = rp.GetSortingWidth()
            let! srp = rp.GetStartingRepl()
            let! rsp = rp.GetReplSpan()
            return (md, mst, smt, sw, srp, rsp)
        }

module MergeRandomMergeSorterBins =
    let projectName = "MergeRandomMergeSorterBins" |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomMergeSorterBins\\Merge\\Data" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "Merge RandomMergeSorterBins, generated by Msce, Mssi, Msrs, and Msuf"
    let samplesPerBin = 1

    // --- Shared Filtering Logic ---
    let private sorterModelTypeForSortingWidth (rp: runParameters) =
        let smt = rp.GetSorterModelType().Value
        let sw = rp.GetSortingWidth().Value
        let has2factor = (%sw % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sw)
        let isMuf6able = (%sw % 3 = 0) && (MathUtils.isAPowerOfTwo (%sw / 3))

        match smt with
        | sorterModelType.Msce -> Some rp
        | sorterModelType.Mssi | sorterModelType.Msrs -> if has2factor then Some rp else None
        | sorterModelType.Msuf4 -> if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> if isMuf6able then Some rp else None
        | _ -> None

    let private mergeConstraints (rp: runParameters) =
        let sw = rp.GetSortingWidth().Value
        let md = rp.GetMergeDimension().Value
        let ft = rp.GetMergeSuffixType().Value
        let divides = (%sw % %md = 0)
        let fillLimit = not (ft.IsNoSuffix && %sw > 64)
        let dimLimit = not (%md > 6 && %sw > 144)
        if divides && fillLimit && dimLimit then Some rp else None

    let paramMapFilter (rp: runParameters) = 
        Some rp 
        |> Option.bind sorterModelTypeForSortingWidth
        |> Option.bind mergeConstraints

    // --- Configurations ---
    module P2 =
        let maxCenterSampledSetSize = 200
        let spans = [ 
            (runParameters.sortingWidthKey, ["16"; "32"; "48"; "64"; "96"; "128"] |> List.map string)
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce; sorterModelType.Mssi; sorterModelType.Msrs; sorterModelType.Msuf4] |> List.map SorterModelType.toString)
            (runParameters.mergeDimensionKey, ["8"])
            (runParameters.mergeSuffixTypeKey, [mergeSuffixType.NoSuffix; mergeSuffixType.VV_1] |> List.map MergeSuffixType.toString)
            (runParameters.startingReplKey, ["0"])
            (runParameters.replSpanKey, ["85"])
        ]
        let host = mergeRandomMergeSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter

    // --- Query Parameter Helpers ---
    let makeQueryParams (repl: int<replNumber> option) (startingRepl: int<replNumber> option) (replSpan: int<replNumber> option)
                        (sw: int<sortingWidth> option) (md: int<mergeDimension> option) (mst: mergeSuffixType option)
                        (smt: sorterModelType option) (odt: outputDataType) =
        queryParams.create (Some projectName) repl odt
            [| (runParameters.sortingWidthKey, sw |> SortingWidth.toString)
               (runParameters.mergeDimensionKey, md |> MergeDimension.toString)
               (runParameters.mergeSuffixTypeKey, mst |> Option.map MergeSuffixType.toString |> UmxExt.stringToString)
               (runParameters.sorterModelTypeKey, smt |> Option.map SorterModelType.toString |> UmxExt.stringToString)
               (runParameters.startingReplKey, startingRepl |> UmxExt.intToString)
               (runParameters.replSpanKey, replSpan |> UmxExt.intToString) |]

    let makeQueryParamsFromRunParams (rp: runParameters) (odt: outputDataType) =
        makeQueryParams (rp.GetRepl()) (rp.GetStartingRepl()) (rp.GetReplSpan()) (rp.GetSortingWidth()) 
                        (rp.GetMergeDimension()) (rp.GetMergeSuffixType()) (rp.GetSorterModelType()) odt

    // --- Refinement ---
    let enhancer (rp : runParameters) : runParameters =
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        rp.WithProjectName(Some projectName).WithRunFinished(Some false).WithId(Some qp.Id)

    let paramMapRefiner (host: mergeRandomMergeSorterBinsHost) (runParametersSeq: runParameters seq) : runParameters seq = 
        runParametersSeq |> Seq.choose host.Filter |> Seq.map enhancer

    let outputDataTypes = 
            [| 
                outputDataType.RunParameters
                outputDataType.SorterEvalBins ""
                outputDataType.SortingSet "EvenSampled"
                outputDataType.SortingSet "HullSampled"
                outputDataType.SortingSet "CenterSampled"
                outputDataType.SortingSet "WinningSampled"
                // The report name is dynamic in the executor, 
                // but we register the base type here.
                outputDataType.TextReport ("" |> UMX.tag) 
            |]

    let project = project.create projectName projectDesc outputDataTypes

    // --- The Executor ---
    let executor (host: mergeRandomMergeSorterBinsHost) (runParameters: runParameters) 
                 (allowOverwrite: bool<allowOverwrite>) (cts: CancellationTokenSource) 
                 (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                // 1. Setup & Initial Reporting
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let repl = runParameters.GetRepl() |> Option.defaultValue (-1 |> UMX.tag)
                ProjectOps.report progress (sprintf "%s Starting Merge Run %s repl %d" (MathUtils.getTimestampString()) %runId %repl)

                // 2. Safe Parameter Extraction (Via Host)
                let! (md, mst, sorterModelType, sortingWidth, srp, rsp) = 
                    host.ExtractDomainParams runParameters 
                    |> Result.ofOption (sprintf "Run %s: Missing required parameters" %runId) |> asAsync

                // 3. Prepare Query Parameters for output IDs
                let qpEvalBins = makeQueryParamsFromRunParams runParameters (outputDataType.SorterEvalBins "")
                let qpEvenSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "EvenSampled")
                let qpCenterSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "CenterSampled")
                let qpWinningSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "WinningSampled")
                let qpHullSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "HullSampled")

                // 4. Initialize Merged Containers
                let mutable mergedEvalBins = sorterEvalBins.createEmpty (%qpEvalBins.Id |> UMX.tag<sorterEvalBinsId>)
                let mutable mergedEvenSet = sortingSet.create (%qpEvenSet.Id |> UMX.tag<sortingSetId>) [||]
                let mutable mergedCenterSet = sortingSet.create (%qpCenterSet.Id |> UMX.tag<sortingSetId>) [||]
                let mutable mergedWinningSet = sortingSet.create (%qpWinningSet.Id |> UMX.tag<sortingSetId>) [||]

                // 5. Connect to the Source Project DB
                let dbSource = new GeneSortDbMp(RandomMergeSorterBins.projectFolder) :> IGeneSortDb

                // 6. Merge Loop
                for r in 0 .. (%rsp - 1) do
                    let currentRepl = %srp + r |> UMX.tag<replNumber>
                    
                    // Construct queries for the source data (RandomMergeSorterBins project)
                    let qpSourceEval = RandomMergeSorterBins.makeQueryParams (Some currentRepl) (Some sortingWidth) (Some md) (Some mst) (Some sorterModelType) (outputDataType.SorterEvalBins "")
                    let qpSourceSet = RandomMergeSorterBins.makeQueryParams (Some currentRepl) (Some sortingWidth) (Some md) (Some mst) (Some sorterModelType) (outputDataType.SortingSet "EvenSampled")

                    // Load source data
                    let! curEval = dbSource.loadAsync qpSourceEval |> AsyncResult.bindResult OutputData.asSorterEvalBins
                    let! curSet = dbSource.loadAsync qpSourceSet |> AsyncResult.bindResult OutputData.asSortingSet

                    // Perform Merges
                    mergedEvalBins <- SorterEvalBins.merge mergedEvalBins curEval
                    
                    // We merge and then immediately sample down to maintain density constraints
                    let evenData = SortingSet.merge mergedEvenSet curSet 
                    mergedEvenSet <- sortingSet.create (%qpEvenSet.Id |> UMX.tag) (SortingSetFilter.sampleBinsEvenly samplesPerBin mergedEvalBins evenData)

                    mergedCenterSet <- SortingSet.merge mergedCenterSet curSet
                    mergedCenterSet <- sortingSet.create (%qpCenterSet.Id |> UMX.tag) (SortingSetFilter.sampleTheCenterBins P2.maxCenterSampledSetSize mergedEvalBins mergedCenterSet)

                    mergedWinningSet <- SortingSet.merge mergedWinningSet curSet
                    mergedWinningSet <- sortingSet.create (%qpWinningSet.Id |> UMX.tag) (SortingSetFilter.sampleWinningBins P2.maxCenterSampledSetSize mergedEvalBins mergedWinningSet)

                    ProjectOps.report progress (sprintf "Merged repl %d for %s" %currentRepl %runId)

                // 7. Calculate Convex Hull from the merged results
                let hullData = SortingSetFilter.sampleBinsConvexHull samplesPerBin mergedEvalBins mergedEvenSet
                let hullSampledSet = sortingSet.create (%qpHullSet.Id |> UMX.tag) hullData

                // 8. Generate DataTable Report
                let reportName = $"MergeReport_{%sortingWidth}_{sorterModelType |> SorterModelType.toString}_{%md}_{mst}" |> UMX.tag<textReportName>
                let qpReport = makeQueryParamsFromRunParams runParameters (outputDataType.TextReport reportName)
                
                let mergeProperties = 
                        [ 
                            ("sortingWidth", (Some sortingWidth) |> SortingWidth.toString)
                            ("sorterModelType", sorterModelType |> SorterModelType.toString)
                            ("mergeDimension", Some md |> MergeDimension.toString)
                            ("mergeSuffixType", mst |> MergeSuffixType.toString)
                        ] |> Map.ofList

                let keyFormatter ((sw:int<sortingWidth>, smt:sorterModelType), key: sorterEvalKey) = 
                            sprintf "%d_%s_%s" 
                                    %sw 
                                    (smt |> SorterModelType.toString) 
                                    (key.AsString())

                let keyToMap (sw:int<sortingWidth>) 
                             (smt:sorterModelType) : Map<string, string> =
                             Map.ofList [("sortingWidth", (Some sortingWidth) |> SortingWidth.toString); 
                                         ("sorterModelType", sorterModelType |> SorterModelType.toString)]

                let tableMap = SorterEvalBins.getPropertyMaps 
                                    mergedEvalBins 
                                    (sortingWidth, sorterModelType) 
                                    mergeProperties 
                               |> Map.ofSeq

                let tableMapNew = SorterEvalBins.getPropertyMapsNew
                                    mergedEvalBins 
                                    (keyToMap sortingWidth sorterModelType)
                                    mergeProperties 
                               |> Map.ofSeq

                let headers, rows = DataTableReport.mapToTabDelimitedStrings keyFormatter tableMap
                let dtReport = DataTableReport.create %reportName headers
                dtReport.AppendDataRows (rows |> Array.toSeq)

                // 9. Persist to DB (Using the project-specific DB provided in the call)
                let! _ = host.ProjectDb.saveAsync qpEvalBins (mergedEvalBins |> outputData.SorterEvalBins) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpEvenSet (mergedEvenSet |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpCenterSet (mergedCenterSet |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpWinningSet (mergedWinningSet |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpHullSet (hullSampledSet |> outputData.SortingSet) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpReport (dtReport |> outputData.TextReport) allowOverwrite

                ProjectOps.report progress (sprintf "Merge Complete: %s" %runId)
                return runParameters.WithRunFinished (Some true)

            with e -> 
                let runId = runParameters |> RunParameters.getIdString
                return! Error (sprintf "Unexpected error in run %s: %s" runId e.Message) |> async.Return
        }