namespace GeneSort.Project.SorterBins

open System

open FSharp.UMX

open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Model.Sorting.Sorter.Ce
open GeneSort.Model.Sorting.Sorter.Si
open GeneSort.Model.Sorting.Sorter.Uf4
open GeneSort.Model.Sorting.Sorter.Rs
open GeneSort.Model.Sorting.Sorter.Uf6
open System.Threading
open GeneSort.Runs
open GeneSort.Db
open GeneSort.Model.Sorting
open GeneSort.Model.Sortable
open GeneSort.SortingOps
open GeneSort.SortingResults
open GeneSort.SortingResults.Bins
open GeneSort.Project
open GeneSort.FileDb
open FsToolkit


module MergeRandomSorterBins_P1 =
    
    let sortingWidths() : string*string list =
        let values = [4; 6; 8; 12; 16; 18; 20; 22; 24] |> List.map(fun d -> d.ToString())
        (runParameters.sortingWidthKey, values)


    let sorterModelTypes () : string*string list =
        let values =         
            [ 
              sorterModelType.Msce; 
              sorterModelType.Mssi;
              sorterModelType.Msrs; 
              sorterModelType.Msuf4; 
              sorterModelType.Msuf6; 
              ]  |> List.map(SorterModelType.toString)
        (runParameters.sorterModelTypeKey, values )


    let startingRepls () : string * string list =
        let values = [ 0; 10; 20; ] |> List.map (fun d -> d.ToString())
        (runParameters.startingReplKey, values)

    let replSpans () : string * string list =
        let values = [ 10 ] |> List.map (fun d -> d.ToString())
        (runParameters.replSpanKey, values)

    let parameterSpans = 
        [ 
            sortingWidths(); 
            sorterModelTypes();
            startingRepls();
            replSpans();
        ]




module MergeRandomSorterBins =

    let projectName = "MergeRandomSorterBins"  |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomSorterBins\\Merge" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "Merge RandomSorterBins, generated by Msce, Mssi, Msrs, and Msuf"
    let collectNewSortableTests = false
    let samplesPerBin = 1


    // Fixed parameters:
    let rngFactory = rngFactory.LcgFactory
    let excludeSelfCe = true
    let allowOverwrite = false |> UMX.tag<allowOverwrite>


    let makeQueryParams 
            (repl: int<replNumber> option) 
            (startingRepl: int<replNumber> option)
            (replSpan: int<replNumber> option)
            (sortingWidth:int<sortingWidth> option)
            (sorterModelType:sorterModelType option)
            (outputDataType: outputDataType) =
             
        queryParams.create
            (Some projectName)
            repl
            outputDataType
            [|
                (runParameters.sortingWidthKey, sortingWidth |> SortingWidth.toString); 
                (runParameters.sorterModelTypeKey, sorterModelType |> Option.map SorterModelType.toString |> UmxExt.stringToString)
                (runParameters.startingReplKey, startingRepl |> UmxExt.intToString);
                (runParameters.replSpanKey, replSpan |> UmxExt.intToString)
            |]


    let makeQueryParamsFromRunParams
            (runParams: runParameters) 
            (outputDataType: outputDataType) =
        makeQueryParams
            (runParams.GetRepl())
            (runParams.GetStartingRepl())
            (runParams.GetReplSpan())
            (runParams.GetSortingWidth())
            (runParams.GetSorterModelType())
            outputDataType




     
     // --- Filters ---

    let sorterModelTypeForSortingWidth (rp: runParameters) =
        let sorterModelKey = rp.GetSorterModelType().Value
        let sortingWidth = rp.GetSortingWidth().Value
        let has2factor = (%sortingWidth % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sortingWidth)
        let isMuf6able = (%sortingWidth % 3 = 0) && (MathUtils.isAPowerOfTwo (%sortingWidth / 3))

        match sorterModelKey with
        | sorterModelType.Msce -> 
                Some rp
        | sorterModelType.Mssi
        | sorterModelType.Msrs -> 
                if has2factor then Some rp else None
        | sorterModelType.Msuf4 ->
                if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> 
                if isMuf6able then Some rp else None
                


    let paramMapFilter (rp: runParameters) = 
        Some rp
        |> Option.bind sorterModelTypeForSortingWidth


    // --- Project Refinement ---

    let enhancer (rp : runParameters) : runParameters =
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)

        rp.WithProjectName(Some projectName)
            .WithRunFinished(Some false)
            .WithId (Some qp.Id)


    let paramMapRefiner (runParametersSeq: runParameters seq) : runParameters seq = 
        seq {
            for runParameters in runParametersSeq do
                    let filtrate = paramMapFilter runParameters
                    if filtrate.IsSome then
                        let retVal = filtrate.Value |> enhancer
                        yield retVal
        }


    let outputDataTypes = 
            [|
                outputDataType.RunParameters;
                outputDataType.SorterEvalBins "";
                outputDataType.SortingSet "EvenSampled";
                outputDataType.SortingSet "HullSampled";
            |]

    let project = 
            project.create 
                projectName 
                projectDesc
                outputDataTypes
                MergeRandomSorterBins_P1.parameterSpans


    let executor
            (db: IGeneSortDb)
            (runParameters: runParameters) 
            (allowOverwrite: bool<allowOverwrite>)
            (cts: CancellationTokenSource) 
            (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                // 1. Setup & ID Extraction
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let repl = runParameters.GetRepl() |> Option.defaultValue (-1 |> UMX.tag)
                ProjectOps.report progress (sprintf "%s Starting Run %s repl %d" (MathUtils.getTimestampString()) %runId %repl)

                // 2. Safe Parameter Extraction
                let! (sorterModelType, sortingWidth, startingRepl, replSpan) = 
                    maybe {
                        let! smt = runParameters.GetSorterModelType()
                        let! sw = runParameters.GetSortingWidth()
                        let! srp = runParameters.GetStartingRepl()
                        let! rsp = runParameters.GetReplSpan()
                        return (smt, sw, srp, rsp)
                    } |> Result.ofOption (sprintf "Run %s: Missing required parameters" %runId) |> asAsync

                // 3. Make the evalBins that will be returned
                let qpEvalBins = makeQueryParamsFromRunParams 
                                            runParameters 
                                            (outputDataType.SorterEvalBins "")

                let mergedSorterEvalBins = sorterEvalBins.createEmpty
                                                (%qpEvalBins.Id |> UMX.tag<sorterEvalBinsId>)

                 // 4. Load and merge the RandomSorterBins for the specified parameters
                let sStartingRepl = (%startingRepl + 1) |> UMX.tag<replNumber>

                let dbRandomSorterBins = new GeneSortDbMp(RandomSorterBins.projectFolder) :> IGeneSortDb

                let qpRandomSorterBins = RandomSorterBins.makeQueryParams 
                                            (Some startingRepl) 
                                            (Some sortingWidth) 
                                            (Some sorterModelType) 
                                            (outputDataType.SorterEvalBins "")

                let! randomSorterEvalBins = dbRandomSorterBins.loadAsync qpRandomSorterBins
                                                |> AsyncResult.bind (OutputData.asSorterEvalBins >> AsyncResult.ofResult)


                let qpEvenSampledSortingSet = RandomSorterBins.makeQueryParams 
                                                    (Some startingRepl) 
                                                    (Some sortingWidth) 
                                                    (Some sorterModelType) 
                                                    (outputDataType.SortingSet "EvenSampled")

                let! evenSampledSortingSet = dbRandomSorterBins.loadAsync qpEvenSampledSortingSet
                                                |> AsyncResult.bind (OutputData.asSortingSet >> AsyncResult.ofResult)


                let sQpRandomSorterBins = RandomSorterBins.makeQueryParams 
                                            (Some startingRepl) 
                                            (Some sortingWidth) 
                                            (Some sorterModelType) 
                                            (outputDataType.SorterEvalBins "")
                let! sRandomSorterEvalBins = dbRandomSorterBins.loadAsync sQpRandomSorterBins
                                                |> AsyncResult.bind (OutputData.asSorterEvalBins >> AsyncResult.ofResult)

                let sQpEvenSampledSortingSet = RandomSorterBins.makeQueryParams 
                                                    (Some startingRepl) 
                                                    (Some sortingWidth) 
                                                    (Some sorterModelType) 
                                                    (outputDataType.SortingSet "EvenSampled")
                let! sEvenSampledSortingSet = dbRandomSorterBins.loadAsync sQpEvenSampledSortingSet
                                                |> AsyncResult.bind (OutputData.asSortingSet >> AsyncResult.ofResult)


                let mergedSorterEvalBins = SorterEvalBins.merge randomSorterEvalBins sRandomSorterEvalBins






                // 5. Save the merged evalBins
                let qpMergedEvalBins = makeQueryParamsFromRunParams 
                                            runParameters 
                                            (outputDataType.SorterEvalBins "")
                let! _ = db.saveAsync 
                                qpMergedEvalBins 
                                (mergedSorterEvalBins |> outputData.SorterEvalBins) 
                                allowOverwrite

                // 5. Final Return
                return runParameters.WithRunFinished (Some true)

            with e -> 
                let runId = runParameters |> RunParameters.getIdString
                let msg = sprintf "Unexpected error in run %s: %s" runId e.Message
                return! async { return Error msg }
        }




