namespace GeneSort.Project.SorterBins

open System

open FSharp.UMX

open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Model.Sorting.Sorter.Ce
open GeneSort.Model.Sorting.Sorter.Si
open GeneSort.Model.Sorting.Sorter.Uf4
open GeneSort.Model.Sorting.Sorter.Rs
open GeneSort.Model.Sorting.Sorter.Uf6
open System.Threading
open GeneSort.Runs
open GeneSort.Db
open GeneSort.Model.Sorting
open GeneSort.Model.Sortable
open GeneSort.SortingOps
open GeneSort.SortingResults
open GeneSort.SortingResults.Bins
open GeneSort.Project


module RandomSorterBins_P1 =
    
    let sortingWidths() : string*string list =
        let values = [4; 6; 8; 12; 16; 18; 20; 22; 24] |> List.map(fun d -> d.ToString())
        (runParameters.sortingWidthKey, values)


    let sorterModelTypes () : string*string list =
        let values =         
            [ 
              sorterModelType.Msce; 
              sorterModelType.Mssi;
              sorterModelType.Msrs; 
              sorterModelType.Msuf4; 
              sorterModelType.Msuf6; 
              ]  |> List.map(SorterModelType.toString)
        (runParameters.sorterModelTypeKey, values )


    let sortableDataFormatKeys () : string * string list =
        let values = [ sortableDataFormat.BitVector512; ] |> List.map SortableDataFormat.toString
        (runParameters.sortableDataFormatKey, values)

    let sorterCounts () : string * string list =
        let values = [ 10000;] |> List.map (fun d -> d.ToString())
        (runParameters.sorterCountKey, values)

    let parameterSpans = 
        [ sortingWidths(); sorterModelTypes(); sortableDataFormatKeys(); sorterCounts() ]



module RandomSorterBins_P2 =
    
    let sortingWidths() : string*string list =
        let values = [4; 6; 8; 12; 16;] |> List.map(fun d -> d.ToString())
        (runParameters.sortingWidthKey, values)


    let sorterModelTypes () : string*string list =
        let values =         
            [ 
              sorterModelType.Msce; 
              sorterModelType.Mssi;
              sorterModelType.Msrs; 
              sorterModelType.Msuf4; 
              sorterModelType.Msuf6; 
              ]  |> List.map(SorterModelType.toString)
        (runParameters.sorterModelTypeKey, values )


    let sortableDataFormatKeys () : string * string list =
        let values = [
                        sortableDataFormat.BitVector512;
                     ] |> List.map SortableDataFormat.toString
        (runParameters.sortableDataFormatKey, values)


    let sorterCounts () : string * string list =
        let values = [ 100;] |> List.map (fun d -> d.ToString())
        (runParameters.sorterCountKey, values)

    let parameterSpans = 
        [ sortingWidths(); sorterModelTypes(); sortableDataFormatKeys(); sorterCounts() ]




module RandomSorterBins =

    let projectName = "RandomSorterBins"  |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomSorterBins" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "RandomSorterBins, generated by Msce, Mssi, Msrs, and Msuf"
    let collectNewSortableTests = false
    let samplesPerBin = 1


    // Fixed parameters:
    let rngFactory = rngFactory.LcgFactory
    let excludeSelfCe = true
    let allowOverwrite = false |> UMX.tag<allowOverwrite>


    let makeQueryParams 
            (repl: int<replNumber> option) 
            (sortingWidth:int<sortingWidth> option)
            (sorterModelType:sorterModelType option)
            (outputDataType: outputDataType) =
             
        queryParams.create
            (Some projectName)
            repl
            outputDataType
            [|
                (runParameters.sortingWidthKey, sortingWidth |> SortingWidth.toString); 
                (runParameters.sorterModelTypeKey, sorterModelType |> Option.map SorterModelType.toString |> UmxExt.stringToString)
            |]


    let makeQueryParamsFromRunParams
            (runParams: runParameters) 
            (outputDataType: outputDataType) =
        makeQueryParams
            (runParams.GetRepl())
            (runParams.GetSortingWidth())
            (runParams.GetSorterModelType())
            outputDataType



    // Implied Parameters:

    let getStageLengthForSortingWidth 
                        (smt:sorterModelType) 
                        (sortingWidth: int<sortingWidth>) : int<stageLength> =
            match %sortingWidth with
            | 4 -> 5 |> UMX.tag<stageLength>
            | 6 -> 20 |> UMX.tag<stageLength>
            | 8 -> 40 |> UMX.tag<stageLength>
            | 12 -> 80 |> UMX.tag<stageLength>
            | 16 -> 100 |> UMX.tag<stageLength>
            | 18 -> 120 |> UMX.tag<stageLength>
            | 20 -> 130 |> UMX.tag<stageLength>
            | 22 -> 140 |> UMX.tag<stageLength>
            | 24 -> 200 |> UMX.tag<stageLength>
            | 32 ->  match smt with
                        | sorterModelType.Msce -> 300 |> UMX.tag<stageLength>
                        | sorterModelType.Mssi -> 300 |> UMX.tag<stageLength>
                        | sorterModelType.Msrs -> 300 |> UMX.tag<stageLength>
                        | sorterModelType.Msuf4 -> 600 |> UMX.tag<stageLength>
                        | _ -> failwithf "Unsupported sorter model type: %A" smt

            | 64 -> match smt with
                        | sorterModelType.Msce -> 600 |> UMX.tag<stageLength>
                        | sorterModelType.Mssi -> 600 |> UMX.tag<stageLength>
                        | sorterModelType.Msrs -> 800 |> UMX.tag<stageLength>
                        | sorterModelType.Msuf4 -> 2000 |> UMX.tag<stageLength>
                        | _ -> failwithf "Unsupported sorter model type: %A" smt

            | 128 -> match smt with
                        | sorterModelType.Msce -> 1200 |> UMX.tag<stageLength>
                        | sorterModelType.Mssi -> 1500 |> UMX.tag<stageLength>
                        | sorterModelType.Msrs -> 1800 |> UMX.tag<stageLength>
                        | sorterModelType.Msuf4 -> 4000 |> UMX.tag<stageLength>
                        | _ -> failwithf "Unsupported sorter model type: %A" smt

            | 256 -> match smt with
                        | sorterModelType.Msce -> 3000 |> UMX.tag<stageLength>
                        | sorterModelType.Mssi -> 3000 |> UMX.tag<stageLength>
                        | sorterModelType.Msrs -> 4000 |> UMX.tag<stageLength>
                        | sorterModelType.Msuf4 -> 6000 |> UMX.tag<stageLength>
                        | _ -> failwithf "Unsupported sorter model type: %A" smt
            | _ -> failwithf "Unsupported sorting width: %d" (%sortingWidth)




     
     // --- Filters ---

    let sorterModelTypeForSortingWidth (rp: runParameters) =
        let sorterModelKey = rp.GetSorterModelType().Value
        let sortingWidth = rp.GetSortingWidth().Value
        let has2factor = (%sortingWidth % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sortingWidth)
        let isMuf6able = (%sortingWidth % 3 = 0) && (MathUtils.isAPowerOfTwo (%sortingWidth / 3))

        match sorterModelKey with
        | sorterModelType.Msce -> 
                Some rp
        | sorterModelType.Mssi
        | sorterModelType.Msrs -> 
                if has2factor then Some rp else None
        | sorterModelType.Msuf4 ->
                if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> 
                if isMuf6able then Some rp else None
                


    let paramMapFilter (rp: runParameters) = 
        Some rp
        |> Option.bind sorterModelTypeForSortingWidth


    // --- Project Refinement ---

    let enhancer (rp : runParameters) : runParameters =
        let sortingWidth = rp.GetSortingWidth().Value
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        let stageLength = getStageLengthForSortingWidth (rp.GetSorterModelType().Value) sortingWidth
        let ceLength = stageLength |> StageLength.toCeLength sortingWidth

        rp.WithProjectName(Some projectName)
            .WithRunFinished(Some false)
            .WithCeLength(Some ceLength)
            .WithStageLength(Some stageLength)
            .WithId (Some qp.Id)


    let paramMapRefiner (runParametersSeq: runParameters seq) : runParameters seq = 
        seq {
            for runParameters in runParametersSeq do
                    let filtrate = paramMapFilter runParameters
                    if filtrate.IsSome then
                        let retVal = filtrate.Value |> enhancer
                        yield retVal
        }


    let outputDataTypes = 
            [|
                outputDataType.RunParameters;
                outputDataType.SorterEvalBins "";
                outputDataType.SortingSet "EvenSampled";
                outputDataType.SortingSet "HullSampled";
            |]

    let project = 
            project.create 
                projectName 
                projectDesc
                outputDataTypes
                RandomSorterBins_P2.parameterSpans


    let executor
            (db: IGeneSortDb)
            (runParameters: runParameters) 
            (allowOverwrite: bool<allowOverwrite>)
            (cts: CancellationTokenSource) 
            (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                // 1. Setup & ID Extraction
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let repl = runParameters.GetRepl() |> Option.defaultValue (-1 |> UMX.tag)
                ProjectOps.report progress (sprintf "%s Starting Run %s repl %d" (MathUtils.getTimestampString()) %runId %repl)

                // 2. Safe Parameter Extraction
                let! (sorterModelType, sortingWidth, stageLength, ceLength, sorterCount, sortableDataFormat) = 
                    maybe {
                        let! smk = runParameters.GetSorterModelType()
                        let! sw = runParameters.GetSortingWidth()
                        let! sl = runParameters.GetStageLength()
                        let! cl = runParameters.GetCeLength()
                        let! sc = runParameters.GetSorterCount()
                        let! sdt = runParameters.GetSortableDataFormat()
                        return (smk, sw, sl, cl, sc, sdt)
                    } |> Result.ofOption (sprintf "Run %s: Missing required parameters" %runId) |> asAsync

                // 3. Create sorting set from run parameters
                let sorterModelGen =
                    match sorterModelType with
                    | sorterModelType.Msce -> 
                        msceRandGen.create rngFactory sortingWidth excludeSelfCe ceLength 
                        |> sorterModelGen.SmmMsceRandGen
                    | sorterModelType.Mssi -> 
                        mssiRandGen.create rngFactory sortingWidth stageLength 
                        |> sorterModelGen.SmmMssiRandGen
                    | sorterModelType.Msrs -> 
                        let opsGenRatesArray = OpsGenRatesArray.createUniform %stageLength
                        msrsRandGen.create rngFactory sortingWidth opsGenRatesArray 
                        |> sorterModelGen.SmmMsrsRandGen
                    | sorterModelType.Msuf4 -> 
                        let uf4GenRatesArray = Uf4GenRatesArray.createUniform %stageLength %sortingWidth
                        msuf4RandGen.create rngFactory sortingWidth stageLength uf4GenRatesArray 
                        |> sorterModelGen.SmmMsuf4RandGen
                    | sorterModelType.Msuf6 -> 
                        let uf6GenRatesArray = Uf6GenRatesArray.createUniform %stageLength %sortingWidth
                        msuf6RandGen.create rngFactory sortingWidth stageLength uf6GenRatesArray 
                        |> sorterModelGen.SmmMsuf6RandGen

                let firstIndex = (%repl * %sorterCount) |> UMX.tag<sorterCount>
                let sortingGenSegment = sortingGenSegment.create 
                                                (sorterModelGen |> sortingGen.Single)
                                                firstIndex 
                                                sorterCount
                let qpSortingSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "") 
                let fullSortingSet = sortingGenSegment.MakeSortingSet (%qpSortingSet.Id |> UMX.tag<sortingSetId>)
                let fullSorterSet = fullSortingSet |> SortingSet.makeSorterSet


                // 4. Create sortable tests
                let! _ = checkCancellation cts.Token
                let sortableTestModel = msasF.create sortingWidth |> sortableTestModel.MsasF
                let qpSortableTests = makeQueryParamsFromRunParams 
                                        runParameters 
                                        (outputDataType.SortableTest "")
                let sortableTests = SortableTestModel.makeSortableTest
                                            (%qpSortableTests.Id |> UMX.tag<sorterTestId>)
                                            sortableTestModel 
                                            sortableDataFormat


                // 5. Evaluate sortings          
                let qpEval = makeQueryParamsFromRunParams 
                                        runParameters 
                                        (outputDataType.SorterSetEval "")
                let sorterSetEval = 
                                SorterSetEval.makeSorterSetEval
                                                (%qpEval.Id |> UMX.tag<sorterSetEvalId>) 
                                                fullSorterSet 
                                                sortableTests 
                                                collectNewSortableTests

                // 6. Map sorterEvals to sortings
                let sortingResultSetMap = SortingResultSetMap.fromSortingSet fullSortingSet
                sortingResultSetMap.UpdateManySortingResults sorterSetEval.SorterEvals


                // 7. Make the evalBins and the sampled sorterSets
                let qpEvalBins = makeQueryParamsFromRunParams 
                                            runParameters 
                                            (outputDataType.SorterEvalBins "")

                let qpEvenSampledSortingSet = makeQueryParamsFromRunParams 
                                                runParameters 
                                                (outputDataType.SortingSet "EvenSampled")

                let qpHullSampledSortingSet = makeQueryParamsFromRunParams 
                                                runParameters 
                                                (outputDataType.SortingSet "HullSampled")

                let sorterEvalBins = sorterEvalBins.create
                                                (%qpEvalBins.Id |> UMX.tag<sorterEvalBinsId>)
                                                sorterSetEval.SorterEvals
                let evenSampledSortingSet = 
                        sortingSet.create
                            (%qpEvenSampledSortingSet.Id |> UMX.tag<sortingSetId>)
                            (SortingSetFilter.sampleBinsEvenly samplesPerBin sorterEvalBins fullSortingSet)

                let hullSampledSortingSet = 
                        sortingSet.create
                            (%qpEvenSampledSortingSet.Id |> UMX.tag<sortingSetId>)
                            (SortingSetFilter.sampleBinsConvexHull samplesPerBin sorterEvalBins fullSortingSet)

                // 4. Saves
                let! _ = db.saveAsync qpEvalBins (sorterEvalBins |> outputData.SorterEvalBins) allowOverwrite
                let! _ = db.saveAsync qpEvenSampledSortingSet (evenSampledSortingSet |> outputData.SortingSet) allowOverwrite
                let! _ = db.saveAsync qpHullSampledSortingSet (hullSampledSortingSet |> outputData.SortingSet) allowOverwrite

            
                progress |> Option.iter (fun p -> 
                    p.Report(sprintf "Saved SortingSet %s for run: %s" (%qpSortingSet.Id.ToString()) %runId))

                // 5. Final Return
                return runParameters.WithRunFinished (Some true)

            with e -> 
                let runId = runParameters |> RunParameters.getIdString
                let msg = sprintf "Unexpected error in run %s: %s" runId e.Message
                return! async { return Error msg }
        }




//module Yab =


//    let executor
//            (db: IGeneSortDb)
//            (runParameters: runParameters) 
//            (allowOverwrite: bool<allowOverwrite>)
//            (cts: CancellationTokenSource) 
//            (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

//        asyncResult {
//            try
//                // 1. Setup & ID Extraction
//                let! _ = checkCancellation cts.Token
//                let runId = runParameters |> RunParameters.getIdString
//                let repl = runParameters.GetRepl() |> Option.defaultValue (-1 |> UMX.tag)
//                ProjectOps.report progress (sprintf "%s Starting Run %s repl %d" (MathUtils.getTimestampString()) %runId %repl)

//                // 2. Safe Parameter Extraction
//                let! (sorterModelType, sortingWidth, stageLength, ceLength, sorterCount, sortableDataFormat) = 
//                    maybe {
//                        let! smk = runParameters.GetSorterModelType()
//                        let! sw = runParameters.GetSortingWidth()
//                        let! sl = runParameters.GetStageLength()
//                        let! cl = runParameters.GetCeLength()
//                        let! sc = runParameters.GetSorterCount()
//                        let! sdt = runParameters.GetSortableDataFormat()
//                        return (smk, sw, sl, cl, sc, sdt)
//                    } |> Result.ofOption (sprintf "Run %s: Missing required parameters" %runId) |> asAsync

//                // 3. Create sorting set from run parameters
//                let sorterModelGen =
//                    match sorterModelType with
//                    | sorterModelType.Msce -> 
//                        msceRandGen.create rngFactory sortingWidth excludeSelfCe ceLength 
//                        |> sorterModelGen.SmmMsceRandGen
//                    | sorterModelType.Mssi -> 
//                        mssiRandGen.create rngFactory sortingWidth stageLength 
//                        |> sorterModelGen.SmmMssiRandGen
//                    | sorterModelType.Msrs -> 
//                        let opsGenRatesArray = OpsGenRatesArray.createUniform %stageLength
//                        msrsRandGen.create rngFactory sortingWidth opsGenRatesArray 
//                        |> sorterModelGen.SmmMsrsRandGen
//                    | sorterModelType.Msuf4 -> 
//                        let uf4GenRatesArray = Uf4GenRatesArray.createUniform %stageLength %sortingWidth
//                        msuf4RandGen.create rngFactory sortingWidth stageLength uf4GenRatesArray 
//                        |> sorterModelGen.SmmMsuf4RandGen
//                    | sorterModelType.Msuf6 -> 
//                        let uf6GenRatesArray = Uf6GenRatesArray.createUniform %stageLength %sortingWidth
//                        msuf6RandGen.create rngFactory sortingWidth stageLength uf6GenRatesArray 
//                        |> sorterModelGen.SmmMsuf6RandGen

//                let firstIndex = (%repl * %sorterCount) |> UMX.tag<sorterCount>
//                let sortingGenSegment = sortingGenSegment.create 
//                                                (sorterModelGen |> sortingGen.Single)
//                                                firstIndex 
//                                                sorterCount
//                let qpSortingSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "") 
//                let fullSortingSet = sortingGenSegment.MakeSortingSet (%qpSortingSet.Id |> UMX.tag<sortingSetId>)
//                let fullSorterSet = fullSortingSet |> SortingSet.makeSorterSet


//                // 4. Create sortable tests
//                let! _ = checkCancellation cts.Token
//                let sortableTestModel = msasF.create sortingWidth |> sortableTestModel.MsasF
//                let qpSortableTests = makeQueryParamsFromRunParams 
//                                        runParameters 
//                                        (outputDataType.SortableTest "")
//                let sortableTests = SortableTestModel.makeSortableTest
//                                            (%qpSortableTests.Id |> UMX.tag<sorterTestId>)
//                                            sortableTestModel 
//                                            sortableDataFormat


//                // 5. Evaluate sortings          
//                let qpEval = makeQueryParamsFromRunParams 
//                                        runParameters 
//                                        (outputDataType.SorterSetEval "")
//                let sorterSetEval = 
//                                SorterSetEval.makeSorterSetEval
//                                                (%qpEval.Id |> UMX.tag<sorterSetEvalId>) 
//                                                fullSorterSet 
//                                                sortableTests 
//                                                collectNewSortableTests

//                // 6. Map sorterEvals to sortings
//                let sortingResultSetMap = SortingResultSetMap.fromSortingSet fullSortingSet
//                sortingResultSetMap.UpdateManySortingResults sorterSetEval.SorterEvals


//                // 7. Make the evalBins and the sampled sorterSets
//                let qpEvalBins = makeQueryParamsFromRunParams 
//                                            runParameters 
//                                            (outputDataType.SorterEvalBins "")

//                let qpEvenSampledSortingSet = makeQueryParamsFromRunParams 
//                                                runParameters 
//                                                (outputDataType.SortingSet "EvenSampled")

//                let qpHullSampledSortingSet = makeQueryParamsFromRunParams 
//                                                runParameters 
//                                                (outputDataType.SortingSet "HullSampled")

//                let sorterEvalBins = sorterEvalBins.create
//                                                (%qpEvalBins.Id |> UMX.tag<sorterEvalBinsId>)
//                                                sorterSetEval.SorterEvals
//                let evenSampledSortingSet = 
//                        sortingSet.create
//                            (%qpEvenSampledSortingSet.Id |> UMX.tag<sortingSetId>)
//                            (SortingSetFilter.sampleBinsEvenly samplesPerBin sorterEvalBins fullSortingSet)

//                let hullSampledSortingSet = 
//                        sortingSet.create
//                            (%qpEvenSampledSortingSet.Id |> UMX.tag<sortingSetId>)
//                            (SortingSetFilter.sampleBinsConvexHull samplesPerBin sorterEvalBins fullSortingSet)

//                // 4. Saves
//                let! _ = db.saveAsync qpEvalBins (sorterEvalBins |> outputData.SorterEvalBins) allowOverwrite
//                let! _ = db.saveAsync qpEvenSampledSortingSet (evenSampledSortingSet |> outputData.SortingSet) allowOverwrite
//                let! _ = db.saveAsync qpHullSampledSortingSet (hullSampledSortingSet |> outputData.SortingSet) allowOverwrite

            
//                progress |> Option.iter (fun p -> 
//                    p.Report(sprintf "Saved SortingSet %s for run: %s" (%qpSortingSet.Id.ToString()) %runId))

//                // 5. Final Return
//                return runParameters.WithRunFinished (Some true)

//            with e -> 
//                let runId = runParameters |> RunParameters.getIdString
//                let msg = sprintf "Unexpected error in run %s: %s" runId e.Message
//                return! async { return Error msg }
//        }


