namespace GeneSort.Project.SorterBins

open System
open System.Threading
open FSharp.UMX
open GeneSort.Core
open GeneSort.Sorting
open GeneSort.Model.Sorting.Sorter.Ce
open GeneSort.Model.Sorting.Sorter.Si
open GeneSort.Model.Sorting.Sorter.Uf4
open GeneSort.Model.Sorting.Sorter.Rs
open GeneSort.Model.Sorting.Sorter.Uf6
open GeneSort.Runs
open GeneSort.Db
open GeneSort.Model.Sorting
open GeneSort.Model.Sortable
open GeneSort.SortingOps
open GeneSort.SortingResults
open GeneSort.SortingResults.Bins
open GeneSort.Project
open GeneSort.FileDb

/// Host type for RandomMergeSorterBins to manage environment-specific spans and filtering
type randomMergeSorterBinsHost = 
    private { 
        _projectDb: IGeneSortDb 
        _parameterSpans: (string * string list) list
        _filter: runParameters -> runParameters option
    }
    static member Create db spans filter =
        { _projectDb = db; _parameterSpans = spans; _filter = filter }

    member this.ProjectDb = this._projectDb
    member this.ParameterSpans = this._parameterSpans
    member this.Filter = this._filter

    member this.ExtractDomainParams (rp: runParameters) =
        maybe {
            let! smk = rp.GetSorterModelType()
            let! sw = rp.GetSortingWidth()
            let! sl = rp.GetStageLength()
            let! cl = rp.GetCeLength()
            let! sc = rp.GetSorterCount()
            let! sdt = rp.GetSortableDataFormat()
            let! md = rp.GetMergeDimension()
            let! mst = rp.GetMergeSuffixType()
            return (smk, sw, sl, cl, sc, sdt, md, mst)
        }

module RandomMergeSorterBins =

    let projectName = "RandomMergeSorterBins" |> UMX.tag<projectName>
    let projectFolder = "c:\\Projects\\RandomMergeSorterBins\\Data" |> UMX.tag<pathToProjectFolder>
    let projectDesc = "RandomMergeSorterBins, generated by Msce, Mssi, Msrs, and Msuf"
    
    let collectNewSortableTests = false
    let samplesPerBin = 1
    let rngFactory = rngFactory.LcgFactory
    let excludeSelfCe = true
    let allowOverwrite = false |> UMX.tag<allowOverwrite>

    // --- Helpers ---

    let getStageLength (smt: sorterModelType) (sw: int<sortingWidth>) : int<stageLength> =
        match %sw with
        | 16 -> 100
        | 32 -> match smt with | Msuf4 -> 600 | _ -> 300
        | 48 -> match smt with | Msuf4 -> 1200 | _ -> 400
        | 64 -> match smt with | Msuf4 -> 2000 | _ -> 600
        | 96 -> match smt with | Msuf4 -> 2800 | _ -> 800
        | 128 -> match smt with | Msuf4 -> 4000 | _ -> 1200
        | 196 -> match smt with | Msuf4 -> 4800 | _ -> 2000
        | 256 -> match smt with | Msuf4 -> 6000 | _ -> 3000
        | _ -> failwithf "Unsupported sorting width: %d" %sw
        |> UMX.tag

    // --- Filter Logic ---

    let private sorterModelTypeForSortingWidth (rp: runParameters) =
        let smt = rp.GetSorterModelType().Value
        let sw = rp.GetSortingWidth().Value
        let has2factor = (%sw % 2 = 0)
        let isMuf4able = (MathUtils.isAPowerOfTwo %sw)
        let isMuf6able = (%sw % 3 = 0) && (MathUtils.isAPowerOfTwo (%sw / 3))

        match smt with
        | sorterModelType.Msce -> Some rp
        | sorterModelType.Mssi | sorterModelType.Msrs -> if has2factor then Some rp else None
        | sorterModelType.Msuf4 -> if isMuf4able then Some rp else None
        | sorterModelType.Msuf6 -> if isMuf6able then Some rp else None
        | _ -> None

    let private mergeDimensionDividesSortingWidth (rp: runParameters) =
        let sw = rp.GetSortingWidth().Value
        let md = rp.GetMergeDimension().Value
        if (%sw % %md = 0) then Some rp else None

    let private limitForMergeFillType (rp: runParameters) =
        let sw = rp.GetSortingWidth().Value
        let ft = rp.GetMergeSuffixType().Value
        if (ft.IsNoSuffix && %sw > 64) then None else Some rp

    let paramMapFilter (rp: runParameters) = 
        Some rp 
        |> Option.bind sorterModelTypeForSortingWidth
        |> Option.bind mergeDimensionDividesSortingWidth
        |> Option.bind limitForMergeFillType

    // --- Configurations ---

    module P1 =
        let spans = [
            (runParameters.sortingWidthKey, [32; 64] |> List.map string)
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce; sorterModelType.Mssi; 
                                                sorterModelType.Msrs; sorterModelType.Msuf4] 
                                                |> List.map SorterModelType.toString)
            (runParameters.mergeDimensionKey, [2; 4;] |> List.map string)
            (runParameters.mergeSuffixTypeKey, [mergeSuffixType.NoSuffix; mergeSuffixType.VV_1]
                                               |> List.map MergeSuffixType.toString)
            (runParameters.sorterCountKey, ["1000"])
        ]
        let host = randomMergeSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter


    module P2 =
        let spans = [
            (runParameters.sortingWidthKey, [16; 32; 48; 64; 96; 128] |> List.map string)
            (runParameters.sorterModelTypeKey, [sorterModelType.Msce; sorterModelType.Mssi; 
                                                sorterModelType.Msrs; sorterModelType.Msuf4] 
                                                |> List.map SorterModelType.toString)
            (runParameters.mergeDimensionKey, [2; 3; 4; 6; 8] |> List.map string)
            (runParameters.mergeSuffixTypeKey, [mergeSuffixType.NoSuffix; 
                                                mergeSuffixType.VV_1] |> List.map MergeSuffixType.toString)
            (runParameters.sorterCountKey, ["1000"])
        ]
        let host = randomMergeSorterBinsHost.Create (new GeneSortDbMp(projectFolder) :> IGeneSortDb) spans paramMapFilter



    // --- Logic ---

    let makeQueryParams repl sw md mst smt outputDataType =
        queryParams.create (Some projectName) repl outputDataType
            [| (runParameters.sortingWidthKey, sw |> SortingWidth.toString); 
               (runParameters.mergeDimensionKey, md |> MergeDimension.toString);
               (runParameters.mergeSuffixTypeKey, mst |> Option.map MergeSuffixType.toString |> UmxExt.stringToString);
               (runParameters.sorterModelTypeKey, smt |> Option.map SorterModelType.toString |> UmxExt.stringToString) |]

    let makeQueryParamsFromRunParams (rp: runParameters) (odt: outputDataType) =
        makeQueryParams (rp.GetRepl()) (rp.GetSortingWidth()) (rp.GetMergeDimension()) (rp.GetMergeSuffixType()) (rp.GetSorterModelType()) odt

    let enhancer (rp : runParameters) : runParameters =
        let sw = rp.GetSortingWidth().Value
        let smt = rp.GetSorterModelType().Value
        let qp = makeQueryParamsFromRunParams rp (outputDataType.RunParameters)
        let sl = getStageLength smt sw
        let cl = sl |> StageLength.toCeLength sw

        rp.WithProjectName(Some projectName)
          .WithRunFinished(Some false)
          .WithCeLength(Some cl)
          .WithStageLength(Some sl)
          .WithId (Some qp.Id)

    let paramMapRefiner (host: randomMergeSorterBinsHost) (runParametersSeq: runParameters seq) : runParameters seq = 
        runParametersSeq |> Seq.choose (host.Filter >> Option.map enhancer)

    let project = project.create projectName projectDesc 
                     [| outputDataType.RunParameters; outputDataType.SorterEvalBins ""; outputDataType.SortingSet "EvenSampled" |]

    let executor (host: randomMergeSorterBinsHost) (db: IGeneSortDb) (runParameters: runParameters) 
                 (allowOverwrite: bool<allowOverwrite>) (cts: CancellationTokenSource) 
                 (progress: IProgress<string> option) : Async<Result<runParameters, string>> =

        asyncResult {
            try
                let! _ = checkCancellation cts.Token
                let runId = runParameters |> RunParameters.getIdString
                let repl = runParameters.GetRepl() |> Option.defaultValue (0 |> UMX.tag)
                ProjectOps.report progress (sprintf "%s Starting Run %s" (MathUtils.getTimestampString()) %runId)

                let! (sorterModelType, sortingWidth, stageLength, ceLength, sorterCount, sortableDataFormat, mergeDimension, mergeSuffixType) = 
                    host.ExtractDomainParams runParameters |> Result.ofOption "Missing parameters"

                // 3. Create sorting set
                let sorterModelGen =
                    match sorterModelType with
                    | sorterModelType.Msce -> msceRandGen.create 
                                                rngFactory sortingWidth excludeSelfCe ceLength |> sorterModelGen.SmmMsceRandGen
                    | sorterModelType.Mssi -> mssiRandGen.create 
                                                rngFactory sortingWidth stageLength |> sorterModelGen.SmmMssiRandGen
                    | sorterModelType.Msrs -> msrsRandGen.create 
                                                rngFactory sortingWidth (OpsGenRatesArray.createUniform %stageLength) |> sorterModelGen.SmmMsrsRandGen
                    | sorterModelType.Msuf4 -> msuf4RandGen.create 
                                                rngFactory sortingWidth stageLength 
                                                (Uf4GenRatesArray.createUniform %stageLength %sortingWidth) |> sorterModelGen.SmmMsuf4RandGen
                    | _ -> failwith "Unsupported model type"

                let firstIdx = (%repl * %sorterCount) |> UMX.tag<sorterCount>
                let genSeg = sortingGenSegment.create (sorterModelGen |> sortingGen.Single) firstIdx sorterCount
                let qpFullSet = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "") 
                let fullSortingSet = genSeg.MakeSortingSet (%qpFullSet.Id |> UMX.tag)
                let fullSorterSet = fullSortingSet |> SortingSet.makeSorterSet

                // 4. Load external tests (Merge Tests)
                let! _ = checkCancellation cts.Token
                let qpTests = SortableMergeTests.makeQueryParams 
                                        (Some (0 |> UMX.tag)) 
                                        (Some sortingWidth) 
                                        (Some mergeDimension) 
                                        (Some mergeSuffixType) 
                                        (Some sortableDataFormat) 
                                        (outputDataType.SortableTest "")

                let dbMergeTests = new GeneSortDbMp(SortableMergeTests.projectFolder) :> IGeneSortDb
                let! rawTestData = dbMergeTests.loadAsync qpTests 
                let! tests = rawTestData |> OutputData.asSortableTest

                // 5. Evaluate
                let qpEval = makeQueryParamsFromRunParams runParameters (outputDataType.SorterSetEval "")
                let eval = SorterSetEval.makeSorterSetEval (%qpEval.Id |> UMX.tag) fullSorterSet tests collectNewSortableTests

                // 6. Binning and Sampling
                let qpBins = makeQueryParamsFromRunParams runParameters (outputDataType.SorterEvalBins "")
                let bins = sorterEvalBins.create (%qpBins.Id |> UMX.tag) eval.SorterEvals

                let qpEven = makeQueryParamsFromRunParams runParameters (outputDataType.SortingSet "EvenSampled")
                let evenSet = sortingSet.create (%qpEven.Id |> UMX.tag) (SortingSetFilter.sampleBinsEvenly samplesPerBin bins fullSortingSet)

                // 7. Save
                let! _ = host.ProjectDb.saveAsync qpBins (bins |> outputData.SorterEvalBins) allowOverwrite
                let! _ = host.ProjectDb.saveAsync qpEven (evenSet |> outputData.SortingSet) allowOverwrite

                return runParameters.WithRunFinished (Some true)

            with e -> 
                return! Error (sprintf "Error in %s: %s" (runParameters |> RunParameters.getIdString) e.Message) |> async.Return
        }